### ISSUE TITLE
Had to revert to "old" version. "New" version too complicated

### ISSUE THREAD

**Issue by brimur** [steveseguin/obsninja#101]
Hi Steve, not so much a bug but was an issue for me. I have used obsninja a few times now to host quizzes for my family (cast my screen) in combination with my own jitsi server. obsninja is great for the realtime screen casting which I was struggling to replicate with my own jitsi server. Last night I noticed the URLs and layout was different. I only needed the screen shareing part and I could not get it to work. It was complicated and I wasnt sure what URLs I should be using but I finally noticed the link to the "old" version and was up and running in seconds after I used that. I hope at some point you will release the server side of obsninja. Thanks again for the old version, it is keeping families connected during this pandemic.

**Comment by steveseguin** [comment]
Hi Brimur

Thank you for the feedback and comment.

I do have another website, called https://Steves.app  which is designed for screen sharing with family and friends.   OBS.Ninja is being targeted more for those trying to produce live video shows with OBS.

What problems were you having with the screen-sharing?  I'd love to fix the problem. From what I can see, the old and new versions are still largely the same.

![image](https://user-images.githubusercontent.com/2575698/80289971-3ebcab80-8710-11ea-84e4-f9646b5d3eb4.png)

**Comment by steveseguin** [comment]
I've updated the alpha-build visually a small amount; reverting some things back.
![image](https://user-images.githubusercontent.com/2575698/80290534-9a3c6880-8713-11ea-9ae8-3077c0315175.png)

Do you have any suggestions on how I could improve things?

Re: server side code, is there a particular reason you'd need the server side code? I'm trying to move away from servers entirely.

**Comment by brimur** [comment]
Hi @steveseguin, thanks for the pointers. I would say I was not using obsninja as intended. I think the confusion for me and my family/friends were the multiple URLs. The invitation URL was asking the guests questions about sharing their camera, screen etc. They were already in a Jitsi Meet room so the only thing I wanted them to do was click the link and see my screen, Nothing they did allowed them to see my screen however. I even tried the URLs myself on my phone but we all only saw a black screen. When I closed the browser on the host we were all disconnected and presented with a QR code page so it was working, just that no one could see anything. When I switched to the old version they saw my screen immediately.

As you said obsninja may not be the correct tool to use. I will use https://steves.app/ going forward or the old version if its still around..

Regarding screen sharing in general, I can only pass audio if I am sharing my whole desktop but there is no audio when sharing an application window which would be a better option so I can do things in the background rather than use another computer. Do you know if its possible to pass audio when sharing just the application window?

Thanks again

**Comment by steveseguin** [comment]
If you wish to pass JUST the audio from the application, you will need to
use Windows "mixer" (part of windows 10) and a virtual audio cable.   (on
Mac OS, you'd use something like SoundFlower of IShowU instead)
The idea is you point the windows app to output audio to the VB cable, and
then select the VB cable in OBS Ninja.

The problem at the moment is I have not set up OBS Ninja with the ability
to select a mic or VB cable in the screen share mode -- so you'd have to
send the audio via the webcam option for now, and the video via the screen
sharing mode.

I have this as a feature that I wish to add, but it has not been heavily
requested so far.  I'll try to add it as an option sometime soon, if you'd
like

https://www.vb-audio.com/Cable/

[image: image.png]

__________________________

Steve Seguin
