### ISSUE TITLE
Comms on macOS does not open the "Rename this group" dialog

### ISSUE THREAD

**Issue by davidperrenoud** [steveseguin/obsninja#1016]
On Windows pressing CTRL and clicking a group on https://comms.cam/alpha/ opens a dialog which allows the user to rename the group.

Actual:
On macOS using Google Chrome 111 pressing CMD or any other key does not open a dialog. It is therefore impossible to rename a group.

Expected:
Pressing CMD or a similar key should open the "Rename this group" dialog. This could be done by listening to [metaKey](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey) in addition to ctrlKey.

**Comment by steveseguin** [comment]
I pushed a fix to beta, alpha, and github.

Thank you for reporting the issue. If you still have issues with it though, please re-open this issue.

**Comment by davidperrenoud** [comment]
A precision for future users: CMD only works when clicking on the "group: ..." text. Clicking outside the text will activate the button as usual as if CMD is not pressed.
