### ISSUE TITLE
OS devices in Group Chat can't handle large groups

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#104]
lex Pettitt (Macbook)Today at 7:15 AM
There seems to be some sort of issue when using ios and desktop together in a group chat. Let me explain what i'm trying to achieve and the results I'm seeing:

- Connect device 1 (mac) into a groupchat > obs.ninja/?roomid=XXXXX
- Connect device 2 (iPhone) into a groupchat 

The above works as expected, the two participants can see eachother and I am able to pull their two streams into OBS. BUT..

If i now connect device 3 (iPad for example) a few strange things start happening. 1) The iPad can only see the video/audio feed from the other iphone in the group chat. You can see that it tried to load the other stream (mac) but it fails and just leaves the empty player there. Although the Mac and the Iphone can see the feed from the iPad. Secondly, and what is more strange. The feed from the iPad (device 3) shows up in director view, but when you try to visit the stream link or put it into OBS.... Nothing. Again just an empty player. It looks like mixing and matching between different OS's aren't playing nicely together in group chat. Let me know if you need any help debugging. Just to add, I have had no problem getting 3+ people in a group chat all on desktop many times before and I've just tried sending 4 feeds from my mac into a group chat using different tabs and that worked fine too.
Update: Had the same issue when using 3 mobile devices (iPhone/iPads)... I think its possible that it's not able to have that many connection at once maybe? Just a gues

**Comment by h1z1** [comment]
Wonder if it's network /connectivity related...Are all devices local to each other?

**Comment by steveseguin** [comment]
I've had a few more reports of mobile devices struggling.

They all are connected via a mesh.

My solution for now will be to switch to an 'avatar' mode, for mobile devices in a group chat situation. Only the main OBS pull feed will have visibility.

I may move towards a server-based approach, but that is counter to the design principals I'm going for with OBS Ninja

**Comment by steveseguin** [comment]
iOS devices can only support up to 3 connections at a time. (h264 at least)  This has been confirmed.

This will be a difficult problem to solve, yet it is an industry wide problem.  I made need to deploy an SFU server, just to support iOS devices, or get fancy with some other ideas.

I will see about other methods of publishing, too, maybe via data channels or something, or via software encoding.

**Comment by steveseguin** [comment]
I've adopted VP8 as the default video codec for iOS devices. This seems to solve the problem. h264 still gets used by OBS for high resolution streams tho.

Not sure about older iOS devices, but w/e at this point. In that case, disable video all together manually.

VP9 can be enabled with a flag in iOS.
