### ISSUE TITLE
A page refresh is required to show the screen after canceling

### ISSUE THREAD

**Issue by KovalevArtem** [steveseguin/obsninja#106]
[Demo](https://www.reddit.com/r/OBSNinja/comments/g80r6u/a_page_refresh_is_required_to_show_the_screen/)
Is it possible to start sharing the screen after canceling without refreshing the page?

**Comment by steveseguin** [comment]
Thank you for the video!! It works well to demonstrate the problem.

I ran into that same issue myself just yesterday. Thank you for reminding me of it and making it an issue.  I think that is something I can fix right now. 

I'm also trying to add some better error handling, so if things break, you have more feedback

**Comment by steveseguin** [comment]
I've corrected this problem in the alpha build.  I've added a safety feature so that you can't double click the button by accident either, trigging it twice.
