### ISSUE TITLE
Icons are broken when using a pinned version URL of VDO.Ninja v23

### ISSUE THREAD

**Issue by rse** [steveseguin/obsninja#1089]
When using v23 in a pinned version of the URL as in https://vdo.ninja/v23/, the icons in the status bar are broken. When using v22 it works just fine.

<img width="672" alt="image" src="https://github.com/steveseguin/vdo.ninja/assets/221273/020bba55-a13f-45e4-a86b-05b38455b89b">

When using the regular URL https://vdo.ninja/ everything is fine, of course. But the pinned version of the URL for v23 is broken.

**Comment by steveseguin** [comment]
I think the issue is v23 hasn't been archived yet, so you are referencing an unknown folder.  As a result, all sub-folders are failing to be found.

ie: https://vdo.ninja/asdfasdfasd/?room=xxxxx&push=xxxxx   - results in the same issue.

I normally push the next archived version once I release the next version into production, but I haven't pushed v24 into production yet.

Great to hear from you, rse.  

I can push the v23 to v23 as a static archive if you'd like?

**Comment by steveseguin** [comment]
Well, I pushed v23.8 to vdo.ninja/v23/, so the issue should be resolved now either way.  I am going to push v24 soon, so it makes sense to do it now anyways.  Thank you

**Comment by rse** [comment]
Perfect. Now it worked just fine again. Many thanks, Steve.

PS: The background is that in VDON-Call (https://caller.studio/) I used a pinned version by default (in the past "v22") and wanted to upgrade to "v23". The reason is that VDON-Call always should use a fixed pinned version of VDO.Ninja. With your change I was able to upgrade it to "v23" now. Thanks!

**Comment by rse** [comment]
Steve, the same issue occurred again with the current version 24: when using the URL https://vdo.ninja/v24/ the icons are broken. Can you check this and fix it once again? Thanks, Steve!

**Comment by steveseguin** [comment]
I pushed an update.  Thank you. You'll just need to refresh.

I'll point out that v24 has had a user report a new audio issue where when using v24, they got some robotic audio in OBS, but v23 didn't have the issue.  v23 though would fail when a guest joined with an audio device that had a very high sample rate set for their audio playback.

 I've not confirmed if other issue reports are related to version yet, as some users have to start OBS as an administrator to avoid audio or firewall issues.

**Comment by rse** [comment]
Thanks for the quick fix, Steve. The URL now works. Great!

**Comment by rse** [comment]
Same issue again with v25, Steve ;-) Please push updates so that https://vdo.ninja/v25/ now works, too. Many thanks.

**Comment by steveseguin** [comment]
Apologies.

In my head I knew I was forgetting something. ;)

I've now created a https://vdo.ninja/v25/, although it probably won't be "locked" for another month or two, as I address any bug reports, etc.  Once I start v26, v25 will stop seeing further updates with the exception of hot fixes.
