### ISSUE TITLE
Unable to use the &minipreview option?!

### ISSUE THREAD

**Issue by rse** [steveseguin/obsninja#1107]
I've tried to use the &minipreview option (in combination with &showpreview) but my self-preview-video is always shown in large and in the main viewport and never at the right top border as the documentation tells. Can it be that this option currently (with v24) is broken? Or do one need to specify more than just &showpreview and &minipreview options? I guess I overlooked a subtle point, but I'm unable to figure out how to get a small overlayed self-preview-video.

**Comment by steveseguin** [comment]
Thank you for reporting the issue.

There's a few issues I've identified, but also some temporary workarounds.

One issue is the mini-preview only works when using using a room or faux-room; ie: ?push=yyyy&view=xxxxx or &room=yyyy.  It will not work if just doing &push=xxx alone.  **I'll fix this** however.

Another issue is &showpreview and &minipreview are conflicting, as I don't think I ever tested with them together.  &minipreview implies that the preview should show already though, so you would only need to use &minipreview for it to work. When used with &showpreview, that takes priority, and it shows a larger preview.  **I'll fix that also** though, so &minipreview takes priority.

I'll try to hot-patch v24 when I get a fix ready, but for now you can try with the following, for example:

**https://vdo.ninja/v24/?minipreview&room=123234234234&webcam**

**Comment by steveseguin** [comment]
I've pushed changes to vdo.ninja/v24/

so this should work now:
https://vdo.ninja/v24/?minipreview&showpreview

v24 might get a few more changes before I start on v25

**Comment by rse** [comment]
Many thanks, Steve! Indeed, now it works as expected from the info of the docs.
