### ISSUE TITLE
Direct video link for a desktop app

### ISSUE THREAD

**Issue by VladimirKhil** [steveseguin/obsninja#1115]
Is it possible to obtain direct video link for a shared camera to display it in a video control inside a desktop app?

Have not found such a discussion in other issues.

Thank you!

**Comment by steveseguin** [comment]
VDO.Ninja can work within a web-view that's within an desktop app. You can then control and interact with it via the web-view messaging API, getting states, volume, and even changing bitrate.  

You can also use a media player that has WHEP support, which maybe some newer versions of FFMPEG might support for example. If you go this path, and face issues configuring VDO.Ninja to use WHEP output, let me know. This approach is pretty limited, but its closer to a traditional video link if you player supports it. Older players may not.

Other solutions might require more complex coding, using a webRTC API framework, or requiring a server to handle a video conversion.

**Comment by VladimirKhil** [comment]
Thank you very much! I have a WPF app which uses quite outdated video engine. So I will go with a WebView approach.
