### ISSUE TITLE
Enable Pre/Post Automation Execution for Software Updates

### ISSUE THREAD

**Issue by amandarino-tei** [steveseguin/obsninja#1136]
Please enable Pre/Post Automation Execution for Software Updates. 

This is already available for Windows Updates... but why it's not available for software updates is beyond me...

We tried doing updates during business hours as recommended by a Ninja technician, but this was disruptive to numerous clients' business operations. 

Now we are finding that when we try to update after hours, some devices (remote laptops/desktops) are not powered on at this time, and as a result, the updates happen when the computer is powered back on first thing in the morning...

This means that the software (M365 Office, Chrome, etc.) is force closed without any notification to the end user. 

I just spent an hour trying to figure out how to make a nice-looking window with line-breaks and everything to notify the end user their software might close for the next few minutes, only to find that I have wasted my time because of this limitation. 

Please provision this feature ASAP... the code is there, you just need to apply it to the right places :)

**Comment by steveseguin** [comment]
@amandarino-tei , I believe you have the wrong Github project.

**Comment by amandarino-tei** [comment]
Sorry, I thought this was where I request features for Ninja RMM.
