### ISSUE TITLE
Feature request: remote exposureCompensation control

### ISSUE THREAD

**Issue by lukaw3d** [steveseguin/obsninja#1142]
I was looking at code related to remoteZoom to try to implement remote exposureCompensation, but it seems an important part of it is obfuscated webrtc.js code. Is there some way to extend remote control outside changing webrtc.js?

**Comment by steveseguin** [comment]
![image](https://github.com/user-attachments/assets/3e755caa-08a7-48ee-8736-7d13d04a940c)

There is a remote exposure compensation control function already, and it's available in lib.js. The director has remote exposure control available to them by default also.

If you want to control exposure outside a room, just be sure that &remote (session.remote) is enabled, else the request will be rejected.  

```
// lib.js ~ line: 31537
function requestVideoHack(keyname, value, UUID, ctrl = false) {
	var msg = {};
	msg.requestVideoHack = true;
	msg.keyname = keyname;
	msg.value = value;
	msg.UUID = UUID;
	msg.ctrl = ctrl;
	session.sendRequest(msg, msg.UUID);
	pokeIframeAPI("request-video-setting", { value: value, keyname: keyname, ctrl: ctrl }, UUID);
}

..
// example code that sets it up and uses it:
var manualLabel = false;
if (i === "exposureTime") {
	if (data.currentCameraConstraints["exposureMode"]) {
		manualMode = document.createElement("input");
		manualMode.type = "checkbox";
		manualMode.id = "manual_" + i + "_" + UUID;
		manualMode.dataset.UUID = UUID;
		manualMode.dataset.keyname = "exposureMode";
		manualMode.onchange = function (e) {
			var value = "manual";
			if (e.target.checked) {
				value = "continuous";
			}
			requestVideoHack(e.target.dataset.keyname, value, e.target.dataset.UUID, true);
			//getById("constraints_" + e.target.dataset.keyname + "_" + e.target.dataset.UUID).value = parseFloat(e.target.value);
			//getById("label_" + e.target.dataset.keyname+ "_" + e.target.dataset.UUID).value = parseFloat(e.target.value);
		};

		manualLabel = document.createElement("label");
		manualLabel.htmlFor = manualMode.id;
		manualLabel.innerHTML = "Auto: ";
		manualLabel.style.marginLeft = "20px";
		if (data.currentCameraConstraints["exposureMode"] == "continuous") {
			manualMode.checked = true;
		}
	}
} 

```

There are some simplified commands though, that can be sent via the API, rather than with requestVideoHack (which can do everything).

'zoom', 'focus', 'pan', and 'tilt'.  These message requests just call their respective functions in lib.js; just simplified versions of requestVideoHack.  webrtc.js just verifies the requests are valid, and runs the corresponding lib function if valid; about 3 lines of code.

That all said, I'd be happy to add in a new API, if you wanted to add a pair of simplified exposure function, like remoteZoom.  I'd also be happy to just slip it all in myself for you, if you have a specific request.

**Comment by steveseguin** [comment]
> I was looking at code related to remoteZoom to try to implement remote exposureCompensation, but it seems an important part of it is obfuscated webrtc.js code. Is there some way to extend remote control outside changing webrtc.js?

https://github.com/steveseguin/vdo.ninja/commit/47775222390842ab89783d6a5a171949a4dc866a#r148120719

I added a simplified exposure function, mostly as a placeholder, with the {exposure: value} calling API for it added to webRTC.

I don't know how you imagine a remote user controlling the exposure, perhaps with some hotkey? Anyways, thank you.  I appreciate the question and the interest in this all.  Keen to help.

**Comment by lukaw3d** [comment]
oooh. I didn't know room + director view had everything

I was just using https://vdo.ninja/?push=__&remote=aa and https://vdo.ninja/?v=__&remote=aa and I thought there was some technical reason why scroll-to-zoom wasn't working despite this being called on scroll: https://github.com/steveseguin/vdo.ninja/blob/47775222390842ab89783d6a5a171949a4dc866a/lib.js#L4750
> session.requestZoomChange(scale, event.currentTarget.dataset.UUID);

**Comment by lukaw3d** [comment]
Well, a possibly useful bookmarklet I made during my ignorance

Auto-adjusting exposureCompensation on the push side:
```js
javascript:/* run on https://vdo.ninja/?push=_*/;
let exposureCompensation = 0;
setInterval(() => {;
  if (session.videoElement) {;
    const canvas = document.createElement("canvas");
    canvas.width = session.videoElement.videoWidth;
    canvas.height = session.videoElement.videoHeight;
    canvas.getContext("2d").filter = "grayscale(1)";
    canvas.getContext("2d").drawImage(session.videoElement, 0, 0);
    const canvasData = canvas.getContext("2d").getImageData(0, 0, canvas.width, canvas.height);
    /* canvasData.data - rgba 1, 1, 1, 255, 1, 1, 1, 255, 1, 1, 1, 255 */;
    let countMinBright = 0;
    let countMaxBright = 0;
    for(let i = 0; i < canvasData.data.length; i += 4) {;
      countMinBright += canvasData.data[i] < 10 ? 1 : 0;
      countMaxBright += canvasData.data[i] > 249 ? 1 : 0;
    };
    const percentageMinBright = countMinBright / (canvasData.data.length / 4);
    const percentageMaxBright = countMaxBright / (canvasData.data.length / 4);
;
    if (percentageMinBright > 0.05) exposureCompensation += 1;
    if (percentageMaxBright > 0.05) exposureCompensation -= 1;
;
    session.streamSrc.getVideoTracks()[0].applyConstraints({ exposureCompensation: Math.min(Math.max(exposureCompensation, -1), 5) });
  };
}, 30_000);

```

**Comment by steveseguin** [comment]
I can make a version of this page, https://vdo.ninja/examples/ptz. which can give you custom controls along the bottom of the page outside of a room.  Focus, exposure, zoom, etc. 

![image](https://github.com/user-attachments/assets/6fa82035-8588-44c8-b8a0-8c1f5443f9fe)

I also have a similar sort of dashboard made for versus.cam, but it controls bitrate/resolution as a viewer, outside a room.

I thought about adding exposure controls to the viewer-page directly, but I don't really know how to include it.  I found a way to do it with zoom, using the mouse wheel lets say, as you can use the mouse wheel without interfering with the picture output

It's possible I can add a little &controlpanel option, which gives you director-style controls as a viewer?  If that would be helpful.  Maybe I can allow you to toggle it on and off via the right-click menu?

Another options could be to use the companion (bitfocus) app or the HTTP API, and you can use your stream deck to then control expsoure.

Happy to add something in -- I just haven't really figured out what's best for a view-only link.  The director room makes a lot more sense to me in this regard.

**Comment by steveseguin** [comment]
> Well, a possibly useful bookmarklet I made during my ignorance
> 
> Auto-adjusting exposureCompensation on the push side:
> 
> ```js
> javascript:/* run on https://vdo.ninja/?push=_*/;
> let exposureCompensation = 0;
> setInterval(() => {;
>   if (session.videoElement) {;
>     const canvas = document.createElement("canvas");
>     canvas.width = session.videoElement.videoWidth;
>     canvas.height = session.videoElement.videoHeight;
>     canvas.getContext("2d").filter = "grayscale(1)";
>     canvas.getContext("2d").drawImage(session.videoElement, 0, 0);
>     const canvasData = canvas.getContext("2d").getImageData(0, 0, canvas.width, canvas.height);
>     /* canvasData.data - rgba 1, 1, 1, 255, 1, 1, 1, 255, 1, 1, 1, 255 */;
>     let countMinBright = 0;
>     let countMaxBright = 0;
>     for(let i = 0; i < canvasData.data.length; i += 4) {;
>       countMinBright += canvasData.data[i] < 10 ? 1 : 0;
>       countMaxBright += canvasData.data[i] > 249 ? 1 : 0;
>     };
>     const percentageMinBright = countMinBright / (canvasData.data.length / 4);
>     const percentageMaxBright = countMaxBright / (canvasData.data.length / 4);
> ;
>     if (percentageMinBright > 0.05) exposureCompensation += 1;
>     if (percentageMaxBright > 0.05) exposureCompensation -= 1;
> ;
>     session.streamSrc.getVideoTracks()[0].applyConstraints({ exposureCompensation: Math.min(Math.max(exposureCompensation, -1), 5) });
>   };
> }, 30_000);
> ```

Is this an auto-exposure compensation function?  It's clever.  Happy to add it in as an auto-compensation function for you to enable?

**Comment by lukaw3d** [comment]
Thank you, but no need! For my use a room+director view does everything I need, and better than auto-exposure compensation
