### ISSUE TITLE
List audio source (alpha channel)

### ISSUE THREAD

**Issue by KovalevArtem** [steveseguin/obsninja#115]
![image](https://user-images.githubusercontent.com/36500228/80761322-08819080-8b43-11ea-976a-001557619a89.png)
I think the previous list of audio source looked prettier...
![image](https://user-images.githubusercontent.com/36500228/80761514-657d4680-8b43-11ea-9207-c7e4c0952493.png)

**Comment by steveseguin** [comment]
I agree 100%.

The thing is, you can now select more than one audio source.  Ctrl + Click to select more than one.  

A drop-down menu lets you select just one. 

People want to have multiple audio sources.

Suggestions?

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/81050569-2d04a200-8e8e-11ea-8028-0e765f775bea.png)
I've been making improvements to this.

**Comment by steveseguin** [comment]
Done. In production.  I made a custom drop down list to make this all work. It was a lot of time, so I dont really want to spend any more time on this unless required.

Screen share mode has a different layout, but it's >70% good enough.

I will make the entire site look pretty at some point, but for now I just want it functional
