### ISSUE TITLE
[Feature Request] Ability to lock Controls on sender side

### ISSUE THREAD

**Issue by manutdkid77** [steveseguin/obsninja#1151]
I like this controlobs feature, and was thinking if we could add a button on the sender side itself to lock/unlock the control panel to prevent from accidental clicks from switching scenes?

![WhatsApp Image 2024-11-02 at 07 59 33](https://github.com/user-attachments/assets/935f205f-4864-4605-bf6c-0a5bc67cf20a)

**Comment by steveseguin** [comment]
I suppose you couldn't just close the control panel?  Did you want to see the output or such?  If so, I suppose just locking the screen also not work?

What about the other lower menu; is that an issue? I can't ultimately prevent the browser's own menu from being misclicked.


Thank you for the request

**Comment by manutdkid77** [comment]
I use an iPhone 13 and if I lock the screen, it doesnt reconnect sometimes and need to close safari for it to re-connect again.

Would it possible if we could only lock the [promptModalInner div](https://github.com/steveseguin/vdo.ninja/blob/46fb393b949529c298b69927ea2f220f4ad36645/index.html#L2545), basically just the contents of the modal/popup which appears on the sender-side when trying to control obs  ?

**Comment by steveseguin** [comment]
![image](https://github.com/user-attachments/assets/2c6bdb4c-96dd-403e-8d03-bc62a19d12c8)

https://vdo.ninja/alpha/?room=xxxxxxxxxx&controlobs

i pushed the change to alpha

**Comment by manutdkid77** [comment]
Wow, that was way too fast, Thank you @steveseguin 

Tested it and it works great.

![WhatsApp Image 2024-11-02 at 11 00 30](https://github.com/user-attachments/assets/34b155a3-5ddc-4976-994c-de665fc60665)
