### ISSUE TITLE
Splashtop for Linux?

### ISSUE THREAD

**Issue by hooptydoopty** [steveseguin/obsninja#1153]
Hello,

We would love the ability to use splashtop for Linux. It's available on Splashtop's own software but not through Ninja. Would love it as a feature.

**Comment by steveseguin** [comment]
Apologies, but I don't know what splashtop is or how you expect to use it with VDO.Ninja. It's some sort of remote desktop software?  Did you want VDO.Ninja to support their remote desktop software or something?

**Comment by hooptydoopty** [comment]
My bad, wrong ninja lol
