### ISSUE TITLE
How can I hide the context menu while user viewing the stream?

### ISSUE THREAD

**Issue by ANV78** [steveseguin/obsninja#1155]
Hi!
Here's my link, for example:
https://vdo.ninja/alpha/?view=...&clean&hidemenu&autostart&easyexit

I noticed that this context menu remains available once the stream starts: 
<img width="1279" alt="Screenshot 2024-12-26 at 01 06 22" src="https://github.com/user-attachments/assets/3aee59f9-2e5a-43ef-98bb-1f8463d78053" />

How can I hide or disable it?

Also, the autostart feature doesn’t seem to be working. Is there any way to start viewing automatically?

**Comment by steveseguin** [comment]
&autostart is for publishing; not viewing.

Things will already auto-view, IF your browser supports it.  Most browsers won't auto play if the video contains sound, so you can mute the audio and then it will auto start, or you can use a different browser.

OBS auto starts and the Electron Capture app also auto starts, regardless of audio.  https://electroncapture.app   

You might also be able to use a command line parameter to start Chrome to disable auto play blocking. I dont' recall what the command is however.

----

As per the context menu appearing when you right-click, I've disabled it when using `&clean` for you now. On alpha, so you should be able to just hard reload.

If you want the menu still,  you can use `&cleanish` instead.

**Comment by ANV78** [comment]
Thank you!
