### ISSUE TITLE
All URLs don't include the port number when hosted on a non standard port

### ISSUE THREAD

**Issue by renthraysk** [steveseguin/obsninja#116]
All URLs don't include the port number when hosted on a non standard port

**Comment by steveseguin** [comment]
Ah.  Okay, yeah I can see that as an issue. It didn't occur to me that someone would be hosting this on a non-standard port, but there are a few places in the code I could update to support that.

**Comment by steveseguin** [comment]
Ive adjusted the code from location.hostname to location.host  
this should fix the issue once I get the code posted here.

**Comment by steveseguin** [comment]
posted to produciton
