### ISSUE TITLE
Indicate version

### ISSUE THREAD

**Issue by KovalevArtem** [steveseguin/obsninja#119]
I am very glad that you decided to assign versions to digital values.
I suggest on each page (especially on the main page) to indicate a numerical version so that it is easier to navigate with them. And it’s easier to report bugs.

Including pages
https://obs.ninja/alpha/
https://obs.ninja/beta/

Example:
![image](https://user-images.githubusercontent.com/36500228/81305901-8b48a500-9087-11ea-8640-495d9a081f31.png)

**Comment by steveseguin** [comment]
Thank you.  I'm adapting to the evolving requirements as needed, and versioning seems to be appropriate at this point.  

I don't yet have a proper deployment integration with Github, but those changes are coming soon too.  Everything takes a lot of work to do, haha.

**Comment by steveseguin** [comment]
This is added; at the bottom of the page, black on dark blue, it will say the current version.
It should also say it in the stats menu
