### ISSUE TITLE
Clean UP repo ; make it easily deployable

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#12]
This will be an on-going work-in-progress task for me.

I'm not the most organized person, and would prefer to just code, but ces't le vie.

**Comment by graywolf336** [comment]
Would you be willing to consider using React or some other UI framework? Or are you wanting to leave it as is?

**Comment by steveseguin** [comment]
Having used React at other companies, I see it being appropriate. A simple UI framework, used for templates and movement animations, perhaps that responded to state changes automatically, could work quite well. I'm perhaps a bit resistant to use React, as it can go from vanilla code to opinionated code quickly, often with a lot of tooling suddenly popping up to make it all work.

If the State-Store was a middle man API, and the Framework kept out of the way of the rest of the code, than that works. I'd still want the UI/UX code to remain incredibly simple and accessible for any-level of developer to hack at. In UI/UX designs, I find buttons are placed close to what they affect, and at a code level, I'd like to imitate within the code when sensible as well. If someone can efficiently develop the code with just a basic notepad editor, then it is a win.

Some further code-level design goals I have in mind with this project are to keep it simple, non-compiling, hackable, and efficient. I've done what I can to avoid frameworks and third-party code, although a small amount of Jquery and such got in. I dislike dependencies. No surprise then that I was thinking that it would be possible to do the UI without needing a third-party framework, but instead just leveraging a set of organized HTML templates hidden away for activation.

From a product level goal, I would like this tool to be hyper-focused on its purpose. Bringing remote feeds into OBS in an intuitive, clean, fast, simple way. The "Group Chat" feature will be the most complicated component I intend to include. This feature is included out of necessity, as mobile devices need two-way support within one-tab (since they do not have the ability to tab away,) webcams on PC can't be shared if in use by Skype/Zoom, and directors need an easier way to manage multiple live feeds.


With the basic functionality of the app hacked out now, I'd like to soon at least start cleaning up and organizing; see where I stand after. I do have a decent idea of where I may cut things up, like the Connection handling and peer messaging, but the UI/UX is being threaded together into a knot currently. React+Redux may be a solution.
