### ISSUE TITLE
Manual language change

### ISSUE THREAD

**Issue by KovalevArtem** [steveseguin/obsninja#138]
There are experts who prefer to use the interface not in their native language, but in English - I think they will not be very happy with the forced switching of the language.

Also, the convenient ability to switch the language will make it easier to notice translation issues.

**Comment by steveseguin** [comment]
Would you want a drop down option or a little flag to let users switch?

I'll remove the forced switch.

**Comment by KovalevArtem** [comment]
How will it be more convenient for you to do this.

**Comment by steveseguin** [comment]
I've made a few changes here to try to accommodate better for this.

In the index file, if you deploy the code, you can specify the default language; in this case, Russian.
<script type="text/javascript" id="main-js" data-translation="ru" src="./main.js"></script>

There is also a drop-down menu that lets you manually select other languages.  It's in the bottom-right corner. I will move this to a better spot and make it look better when I re-design the UI.

You can also specify the language via the URL bar still; &ln=ru 

I will also look more into the previously mentioned Translation service and others options, so I can keep the translation files up to date.
