### ISSUE TITLE
re: iOS devies, I'll probalby disable the video if it is not 'active' and in view

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#149]
re: iOS devies, I'll probalby disable the video if it is not 'active' and in view
but this will mean that when they come into view, it will take a moment for the quality to ramp up

**Comment by jedeyenight5** [comment]
Is there a way we can disable this feature? I use OBS.Ninja for a live show where we swap between cameras. The quality being terrible pretty much renders this unusable. For what it,s worth, the quality never seems to return to normal on iOS devices once I have switched away from the active camera in OBS.

**Comment by steveseguin** [comment]
Yep, I did add an option to disable the scenes from changing bitrate if OBS indicates they are visible or not.

Add **&obsoff** to the view link.   That will disable all related events from OBS.

I really value this type of feedback, so thank you. I will fix the issue with iOS devices, as they should ramp back up, and if not, I'll disable it by default for iOS devices. I didn't realize that was an issue; my apologies.

Other than iOS devices and the issues there, how bad do you find the quality ramp up?  I can make this feature optional, rather than the default.

**Comment by jedeyenight5** [comment]
Quite impressed that you replied to this so fast. Funny enough, we are are actively troubleshooting right now and implemented that change to find immediate success. Seriously you need to create a Patreon or something to earn a little bit of cash on the side for this. 

> Other than iOS devices and the issues there, how bad do you find the quality ramp up? I can make this feature optional, rather than the default.

We never saw any quality ramp up. When I change from the scene in OBS and change back the quality drops from 1080p to like 480p and very pixelated. It then stays there and does not ever return to normal again.

**Comment by steveseguin** [comment]
Thank you for the kind comment.

I've confirmed the issue with OBS + iOS.    iOS claims it has recovered, even claiming the resolution is 720p, but it clearly isn't.  From what I can see this is iOS specific still, so I will simply exclude iOS devices for now as a fix.

I will also make it so non-iOS devices ramp up from a higher bitrate starting position, so quality will be better when rapidly switching.  I'll need to keep tinkering with this based on feedback, but the benefits of CPU savings are pretty big if I can manage to make it work.

**Comment by steveseguin** [comment]
Pushed into production.
