### ISSUE TITLE
Reconnection does not occur when network connection is lost

### ISSUE THREAD

**Issue by kpcenti** [steveseguin/obsninja#151]
When switching between networks or lost connection, the broadcaster does not reconnect on it's own or signal to the user that connection has been lost. 
For example switching between WiFi to Mobile Data(ex: 4G LTE), once the connection is dropped. The feed stops and Remote Control Panel for the feed in the Room's Control Center disappears. While the broadcaster end continues with no indication of a lost connection or to reconnect.

**Comment by steveseguin** [comment]
This has been on my agenda for a while now; I think I recently figured out a way I can enable reconnecting though.  Reconnecting does come with it some security concerns, but I have some ideas there, too.

Thank you for the issue.

**Comment by steveseguin** [comment]
I've added some logic here in the newest release that I hope addresses this issue. It may not work in every case, as there are some edge cases where it will try just once to reconnect and then fail, but I'll keep at improving it still. Reconnection times should also be faster now.

**Comment by steveseguin** [comment]
Should be fixed in all cases with the upcoming release
