### ISSUE TITLE
Reorganize the Add Camera to OBS screen for more clarity

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#153]
Every now and then I have to run inexperienced guests through this screen. They are usually a bit confused, especially by the "CLICK HERE WHEN READY" button being all the way to the top.

It would make more sense if the button was at the bottom of the screen. Dialogs flow better from top to bottom and from left to right. A different flow would make things for my guests (and for me) much easier.

I suggest a numbered flow from top to bottom.

Example:

## Add your camera and microphone to OBS

1. Select the video source [pulldown with camera sources]

2. Select the video settings [radio buttons for resolution]

3. Select the audio source(s) [audio source selector]

[CLICK HERE AFTER YOU ARE DONE] (button)

**Comment by steveseguin** [comment]
Thank you. I'll continue to make such improvements to make it friendlier for guests.

I've made a minor such improvement to the audio selector tonight; I'll see what I can do with your feedback though to further improve things.

thank you

**Comment by chrismarquardt** [comment]
I understand your reasoning. People sometimes won't scroll if they don't have a strong indication that something's below the fold. 

How about something like this? Maybe even with the button fixed to the top, no matter where you scroll?

![UI_suggestion](https://user-images.githubusercontent.com/2527608/82124239-fc7e0b80-979d-11ea-968e-b0b26abf195e.png)

**Comment by steveseguin** [comment]
I quickly played around on Alpha to see if I could make any quick wins here.

1. moved the button down, below the video.
2. Hide the resolution settings as a 'settings' option for the video (triggers the sub-menu to appear when clicked)
3. made some color changes to make it a bit more pleasing for my eye.

![image](https://user-images.githubusercontent.com/2575698/82127367-00e7fb80-9781-11ea-8796-32ffcde0a442.png)
![image](https://user-images.githubusercontent.com/2575698/82127370-05acaf80-9781-11ea-94f9-15a226530dbc.png)

I'm looking for quick wins to make things 'better', even if its still not perfect, as I need to triage issues. I do realize though that this page needs a lot more work and probably a larger re-think

**Comment by chrismarquardt** [comment]
Steve, I understand that you have a lot on your plate, and I appreciate your quick reaction. This is indeed better, I've just had a quick play with it on beta. Thanks so much, no go and concentrate on the really important things :)

**Comment by chrismarquardt** [comment]
Current version is good. Closing.
