### ISSUE TITLE
Using the 'remove from group scene' button, also disables video on solo pages

### ISSUE THREAD

**Issue by CyBeRoni** [steveseguin/obsninja#158]
When you have a group scene set up and you remove a feed from it, that feed also disappears from the solo view. Can be worked around by changing the 'scene=1' parameter in the URL to something else.

**Comment by steveseguin** [comment]
Thank you for this bug report; that's an issue and shouldn't be happening. I'll fix it

**Comment by steveseguin** [comment]
This has been fixed in the upcoming code release.  Thank you again.

The solution is just a temporary solution; there will be different scenes in the future, so the solo and group scenes will have different triggers tied to them.
