### ISSUE TITLE
Camera-only page still receives feeds from others in group

### ISSUE THREAD

**Issue by CyBeRoni** [steveseguin/obsninja#159]
I found that using the camera-only url (with `&view`) which is supposed to only send video, I would often still see any incoming feeds on that page. 

It seemed to me that changing the view parameter to `view=something` rather than just `view` prevented this behaviour.

**Comment by over9001** [comment]
Thank you for posting this fix, CyBeRoni!

And thank you steveseguin for obsninja! 

Can confirm this simple fix works.

**Comment by CyBeRoni** [comment]
This problem appears to originate here: https://github.com/steveseguin/obsninja/blob/master/main.js#L87

Where `session.view` is assigned `""` (empty string) which later fails a test, here: https://github.com/steveseguin/obsninja/blob/master/main.js#L552 causing the page to play all incoming streams.

**Comment by steveseguin** [comment]
I think this is fixed now; as of version 6.

**Comment by CyBeRoni** [comment]
From quickly testing that indeed seems to work as expected now.
