### ISSUE TITLE
when ninja cam is grouped in OBS, audio fails

### ISSUE THREAD

**Issue by danpowpow** [steveseguin/obsninja#162]
I have some goups in OBS - with border frames, animated titles etc. When I add the ninja browser link into the group, the audio fails, and will not work when transistioning back to the scene.
Pulling the browser-link source back out of the group, the audio works correctly. It closes when sceneing away, and comes back in when activating the scene.
Any ideas why this could be a case.
OBSNinja is a gamechanger!

**Comment by steveseguin** [comment]
I mentioned this on reddit I think already, but does this error occur on https://obs.ninja/beta ?

**Comment by steveseguin** [comment]
In OBS, if the OBS.Ninja link is not in an active scene, the audio will not work. There are a few ways to get around this, perhaps by using &novideo in the Electron App and output Audio to a virtual Audio cable.  I personally however just duplicate the element into different different scenes, pushing the element out of sight; it's easy enough to do to fix my scenarios.

Not sure about the issue with Groups. This sounds more like an issue with OBS Browser Source than OBS.Ninja. I welcome suggestions on possible fixes.

**Comment by danpowpow** [comment]
thanks for giving this more thought, Steve.
i'm aware of the 'active scene' rule - it makes sense to me, and I do as you do and order items down out of site if i just need the audio.
I will explore the browser source's functionality more thoroughly. if the grouping issue is with that rather than ninja, I can direct my comments over to the OBS bugtracker!

**Comment by steveseguin** [comment]
I think this has been fixed.
