### ISSUE TITLE
Minified main.js file

### ISSUE THREAD

**Issue by nielsverhoeven** [steveseguin/obsninja#164]
Hi Steve,

I've forked your work a couple of days ago to make some specific adjustments for my needs (color codings and stuff). I've noticed you've minified the main.js file a couple of days ago. Can you please undo this so I can update my fork with your code optimizations again?

**Comment by steveseguin** [comment]
Sorry for the slow response; just noticing this comment now.

main.js is now unminified, and the code base has been updated.

Also, I think the &view&push=xxx&room=yyy bug has been fixed. You should not need to do &view=none anymore
