### ISSUE TITLE
Feature request: Allow the mic mute / video mute / question button size to be customised

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#166]
Especially in a smaller group window, the buttons sometimes cover up almost an entire participant. It would help if the buttons could be customised, moved0 or at least resized.

**Comment by steveseguin** [comment]
buttons can be removed now, using &cleanoutput, and I've made them about 30% smaller and 50% transparent.  I'll continually try to improve this; I have some ideas for a revamp of the UI, but it will probably need to wait until after this next release of bug fixes.

**Comment by steveseguin** [comment]
improved the design of the mute buttons; also moved to the center.

You can hide them with &clean or &cleanoutput

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/85810433-06921300-b729-11ea-8b74-2c6e56a28661.png)

**Comment by chrismarquardt** [comment]
The current iteration has worked well, so feel free to close
