### ISSUE TITLE
add a hangup button

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#174]
add a button that disconnects and kills the app.

dangerous as anything, but whatever.

**Comment by chrismarquardt** [comment]
+1. So far I've been telling my guests "just close the Chrome tab to hang up" but a button would make that simpler. Worst case they have to refresh to join again.

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/85253628-9afc2d00-b42c-11ea-9f99-73a665813d54.png)

It's added to development; will be pushed with the next update.
