### ISSUE TITLE
Feature suggestion: flat links instead of parameters

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#182]
Here's an esoteric one. I send obs.ninja invitation links to guests for recording sessions, which works great with &view and &push on the same URL. However, links with many parameters will sooner or later get long and unwieldy. Email systems might even break them up and make them harder to copy/paste. The parameters might even make some of the recipients want to play with the numbers when you don't really want that.

I can of course use a link shortener, but would having something like that built into obs.ninja make sense? 

An alternative link format might hide the parameters in a string.

Instead of 
obs.ninja/?view=xxxx&push=yyyy&stereo=1&videobitrate=500&audiobitrate=64&cleanoutput
use something like
obs.ninja/vxxxxpyyyys1vb500ab64cl
and/or obfuscate with base64 
obs.ninja/dnh4eHhweXl5eXMxdmI1MDBhYjY0Y2w
or just rot13
obs.ninja/ikkkkcllllf1io500no64py

Targeted towards copy/paste-challenged people or those who you don't really want to mess with the parameters. Not tamper-proof, but good enough for most cases.

Let me know if that's a bad idea. I'm happy to keep using my link shortener.

**Comment by steveseguin** [comment]
a few thoughts; 

I already do obs.ninja/roomnamehere , so a shortner runs into conflict with that.  In the near future rooms will have 'settings', so when you connect to a room it will download a bunch of custom room-specific settings already.  

Rewriting URLs like obs.ninja/xxxxxx requires a webserver modification to make work; other people deploying OBS.ninja to their own servers wouldn't likely support that without server-side changes. Not sure many people would know how to set that up.

I'm not really sure where I'd put this shortner in the UI yet. Once a link has been made into a shortner, it becomes hard to change -- which I get is a benefit, but it can also be a problem if it automatically always creates shortened links.

view links are primarily for the OBS side of things; when inserting into OBS so I'd think you don't really need it to be guest-friendly, as the guests aren't seeing it. Nor would you be emailing these links really.

That all said, what I'm thinking is I can add to the "create invite link" option an optional checkbox to shorten links.  I could do something then like "obs.ninja?s=JdiMM5m15Mfkioei3F365Djkj  for now to condense links and see how it gets used.

I like the idea, though I'm just struggling to find a good way to implement it.

**Comment by chrismarquardt** [comment]
Maybe a second additional set of shorter alternative parameters might be a compromise? 

&videobitrate &vb
&audiobitrate &ab
&stereo &s
&view &v
&push &p
...

**Comment by steveseguin** [comment]
&push will need more work, but the others I have completed.

Thank you for the suggestion.
