### ISSUE TITLE
limit bandwidth when privacy is enabled and TURN server has not been changed

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#186]
Not 100% sure about this, but the Privacy option isn't really designed to be use in a group chat room. That puts a heavy cost on my poor TURN servers.

I've seen it used this way now though, and so I may need to limit access of it in some way so that it doesn't get abused.  Something like limiting total bandwidth per IP to 3mbps might be something I can try; that's enforceable I think.

I could also just make the privacy flag not available within the context of a group chat room. 

At the moment this doesn't matter, as the cost is being absorbed by the new sponsors, but it's an option I can use in the long term if it becomes a big problem. meh.

**Comment by steveseguin** [comment]
investigated; I can limit users and limit bandwidth.  Not going to add it until it becomes an issue.

**Comment by jcalado** [comment]
TURN clients are now capped at 5Mbps.
