### ISSUE TITLE
&videobitrate too low when viewing from room participants

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#207]
I have multiple people join a room:
../?push=p1&room=r1&videobitrate=40&stereo=1&audiobitrate=16&codec=vp9
../?push=p2&room=r1&videobitrate=40&stereo=1&audiobitrate=16&codec=vp9
../?push=p3&room=r1&videobitrate=40&stereo=1&audiobitrate=16&codec=vp9
I then use the electron app to to pull their video and audio streams at a higher bitrate for recording:
../?view=p1,p2,p3&stereo=1&videobitrate=200&audiobitrate=64&codec=vp9&nocursor&sink=...

The audiobitrate received is the expected 64kbit/s, but the video bitrate received stays under 60kbit/s while it should be at 200kbit/s each.

**Comment by steveseguin** [comment]
I can't seem to replicate yet. 
![image](https://user-images.githubusercontent.com/2575698/85316873-7edba880-b48b-11ea-9b02-cc8b22711550.png)

https://obs.ninja/?view=p1a,p1b,p1c&stereo=1&videobitrate=2000&audiobitrate=64&codec=vp9

https://obs.ninja/?push=p1b&room=r1a&videobitrate=40&stereo=1&audiobitrate=16&codec=vp9
https://obs.ninja/?push=p1a&room=r1a&videobitrate=40&stereo=1&audiobitrate=16&codec=vp9
https://obs.ninja/?push=p1c&room=r1a&videobitrate=40&stereo=1&audiobitrate=16&codec=vp9

**Comment by chrismarquardt** [comment]
Strange. I'll test again.

**Comment by chrismarquardt** [comment]
Just tested and now it works as expected. I'm puzzled, not sure if I had a typo or what it was. Guess you can close this and I'll keep watching if it happens again.
