### ISSUE TITLE
When viewing multiple streams in one browser tab, fullscreen changes bitrate on other tiles

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#211]
Found an obscure one.

**1. Setup:**

Open three Chrome windows:
 
Side A:
https://obs.ninja/?view=v001,v002&push=g001&videobitrate=500&codec=vp9&webcam

Side B / push B camera, view A camera:
https://obs.ninja/?view=g001&push=v001&videobitrate=500&codec=vp9

Side B / screen share:
https://obs.ninja/?push=v002

**2. Operate**

Browser A now shows 3 tiles: Cam A, Cam B, Screen B

Video bitrates in browser B: 
- about 500kbit/s for B camera stream
- about 10kbit/s for B shared screen

Now press the pseudo fullscreen X on the B screenshared tile.
Press it again to un-pseudo-fullscreen. 

**3. Expectation**

B camera stream still displayed to A at 500kbit/s 

**4. Actual behaviour**

Side A gets cam B's videobitrate at 40kbit/s now. To make it go 500kbit/s again, A has to pseudo fullscreen Cam B tile and then pseudo un-fullscreen it.

**Comment by chrismarquardt** [comment]
Here's the simplified version to test this:

Browser 1: https://obs.ninja/?view=blah1&push=blah2&videobitrate=1000
Browser 2: https://obs.ninja/?view=blah2&push=blah1&videobitrate=1000

1. Check debug box for received video bitrate (shows around 1000)
2. Pseudo fullscreen the sending video followed by making it small again
3. Check debug box for received video bitrate (is now under 40)

**Comment by steveseguin** [comment]
Thank you for reporting this.  I have confirmed the issue.  A million blessings be on you.

**Comment by steveseguin** [comment]
fixed.  Thank you again. 

Code updated on https://obs.ninja/beta and should be available on production in the next day or so.
