### ISSUE TITLE
don't show the pseudo maximize icon when app runs in the electron app 

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#219]
When running the dedicated electron app, mouse hover reveals the maximise icon in the right top, even when &nocursor is enabled.

**Comment by steveseguin** [comment]
great catch. thank you

**Comment by steveseguin** [comment]
I made an update to Beta for this, though I'll have a complete solution ready tonight I think.

**Comment by steveseguin** [comment]
done.  Made a few other such related improvements as well.

**Comment by chrismarquardt** [comment]
fix confirmed here, thanks!
