### ISSUE TITLE
&stereo parameter makes share buttons disappear

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#220]
Camera/screen share buttons are hidden when using
https://obs.ninja/?push=something09&stereo 

Camera/screen share buttons show when using
https://obs.ninja/?push=something09&s
https://obs.ninja/?push=something09&stereo=1
https://obs.ninja/?push=something09&s=1

**Comment by steveseguin** [comment]
another great catch; thank you

**Comment by steveseguin** [comment]
fixed.
