### ISSUE TITLE
Feature request: show outgoing videobitrate and audiobitrate in local stats window

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#221]
Add a few more stats to the outgoing stats:
- outgoing videobitrate
- outgoing audiobitrate
- outgoing video codec

Maybe even some of the configuration parameters:
- automatic gain control: on/off
- echo cancellation: on/off

Purpose: general curiosity and debugging help

**Comment by steveseguin** [comment]
totally understood.

Stats are a pain to access, but the goal is expand this.

One challenge is outgoing videos can have many connections, so it's not just one outbound stream --  but potential dozens.  

in the mean while, Chrome://webrtc-internals is the solution.

**Comment by chrismarquardt** [comment]
webrtc-internals does the job nicely. Closing
