### ISSUE TITLE
Show the guest's URL in stats window

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#222]
Use case: If I can't use a link shortener for guest URLs, I send them via email. I've had to do lengthy debugging on a few sessions where it later turned out they didn't fully copy the long URL because it had wrapped in their email. If I could see the URL that their browser opened, I could have spotted this quicker.

**Comment by chrismarquardt** [comment]
Just had another case last night where knowing the guest's URL would have really helped. 

I received my three regular guests via OBSN, I had given them new links for a room, incluing &novideo and all the bells and whistles. When things didn't work as expected (and as tested on my side), I spent way too much time until I found out that one of them hadn't in fact used the new link, but instead had used a bookmark they saved a few weeks ago.

Seeing their link would've allowed me to pinpoint the culprit right away.

**Comment by steveseguin** [comment]
The following data has been added 'behind the scenes' of the app already, so transferred from viewer to sender.

```
msg.info.label = session.label;
msg.info.width = session.width;
msg.info.height = session.height;
msg.info.quality = session.quality;
msg.info.maxvb = session.maxvideobitrate;
msg.info.maxviewers = session.maxviewers;
msg.info.stereo = session.stereo;
msg.info.aec = session.echoCancellation;
msg.info.agc = session.autoGainControl;
msg.info.denoise = session.noiseSuppression;
msg.info.useragent = userAgent;

```


and 


```
msg.info.label = session.label;
msg.info.stereo = session.stereo;
msg.info.vb = session.bitrate;
msg.info.ab = session.audiobitrate;
msg.info.codec = session.codec;
msg.info.userAgent = userAgent
```

the actual URL I'll need to ensure is safe to share, since there could be privacy concerns there, but I am revealing quite a bit with this approach.  I was hoping to show it in the STATS page ---  but I need to organize the stats page better to fit it all

**Comment by chrismarquardt** [comment]
The stats window changes showing URL parameters solve this for me. Thanks for working on this!

Closing.
