### ISSUE TITLE
Feature suggestion: allow guests to see themselves mirrored

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#225]
"I'm mirrored" is probably the one thing I hear most from guests. I know they aren't actually mirrored, but other software like Skype gives them a mirrored preview that they are now used to.

Allow guests to mirror their own local preview without changing what gets sent to the recipient. Maybe even make that a default and allow mirroring to be controlled through a URL parameter.

**Comment by steveseguin** [comment]
That's fascinating.  hrm.   I'll need to chew on this.  wouldn't be too hard to implement by default
