### ISSUE TITLE
Group chat doesn't show iOS cameras

### ISSUE THREAD

**Issue by isaacnicholas** [steveseguin/obsninja#236]
When running a group chat, iOS cameras do not show up in the group window (the ?room query param). However, they do show up in the director feed and I can import them into OBS using the link provided there. I also tested in the old version and it works fine there.

**Comment by doug86i** [comment]
This is a known limitation for IOS devices.

I believe they can only support 3 streams before things go wrong.

We have:
1: Director view
2: Room scene
3: OBS feed

Meaning there are no free streams to send to the other participants.

I'm sure Steve will clarify but I imagine in the old version, it simply didn't check and the devices would crash as more people joined the room.

**Comment by steveseguin** [comment]
As mentioned, iOS only allows for 3 streams at a time, so I restrict them in group rooms.

You can disable it with I think &forceios , but after 3 streams are used, things will start going "black" for some viewers.

**Comment by steveseguin** [comment]
I will fix this problem long term, by means of a server solution to assist , but due to the cost and complexity, it isn't a priority for me right now

**Comment by steveseguin** [comment]
fixed wihtout servers. whew.
