### ISSUE TITLE
Director with noaudio & novideo

### ISSUE THREAD

**Issue by ersheff** [steveseguin/obsninja#244]
Having a director page that still allows for mute, add/remove from scene, etc with novideo and noaudio flags would be great. Could reduce system load for directors that also need to be IN the scene (i.e. have a second window open with a regular room feed).

Might be a way to address issue #192 ?

**Comment by steveseguin** [comment]
Should be easy enough to address.  Thank you.

**Comment by steveseguin** [comment]
@ersheff 

&novideo and &noaudio now work in the control room.  

The code is currently on BETA for testing:
https://obs.ninja/beta/

**Comment by ersheff** [comment]
Amazing. Works great. Thanks, Steve!
