### ISSUE TITLE
draw onto streams

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#254]
It may sound silly but is there an option to "draw" on a stream for diagrams or other?

**Comment by steveseguin** [comment]
You can draw via OBS -> OBS Virtualcam of course

**Comment by jcalado** [comment]
Not to talk down on the suggestions but this seems like out of scope for OBSNinja.

**Comment by lobstrain** [comment]
I agree. OBS and other such software already have ways to telestrate, just a matter of looking them up.

**Comment by steveseguin** [comment]
Pester me and I may add this still, but it's not a priority
