### ISSUE TITLE
Improve director page layout

### ISSUE THREAD

**Issue by jcalado** [steveseguin/obsninja#255]
I feel like for a first time user the amount of information on screen is adequate. But for returning users there's maybe a bit too much of things being repeated or over-explained.

I'd suggest trimming it down to:
![image](https://user-images.githubusercontent.com/26873/91351058-8d25a800-e7df-11ea-9044-77b3e44f653f.png)

Lower right (?) button could hold additional info that now lives on the page, as well as the info now under the "Click Here for a quick overview and help" button.

**Comment by steveseguin** [comment]
I made some improvements.  It still is far from what you proposed, but I hope it's a bit better.

![image](https://user-images.githubusercontent.com/2575698/91417536-f547ae80-e81e-11ea-8f39-77910ddf2d53.png)

**Comment by jcalado** [comment]
Do you see anything like the wireframe above being a possibility? 
Or do you envision it going in some other direction?
