### ISSUE TITLE
Improve support for TURN SERVERs; guide and/or more servers

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#26]
I think I can do this, perhaps via a URL parameter, but if people are having problems with connections, the can just optionally get one for their own private use for pennies or even free.

I just can't affordably scale a public turn server myself.

I might be able to do a guide on setting a turn server, or offering to support them for a fee,  but it's not a priority right now.  My goal is to do 100% free ultimately.

**Comment by graywolf336** [comment]
If you was to write a bash script so that it could easily be deployed, I would offer to host one or two of them.

**Comment by steveseguin** [comment]
I really appreciate that. I might just take you up on that offer at some point.

**Comment by steveseguin** [comment]
I made my TURN server public, for now, to reduce the number of issues I've had to deal with.  Lets me debug easier.

You can override my TURN server settings via an URL parameter ; this lets you use your own, which might be better for you anyways.  I've included a basic guide on how to setup a TURn server, although I need to add to it how to do IPv6 support and I need to automate the deployment so anyone can do it with ease.

So, I'll leave this task open for now,

**Comment by steveseguin** [comment]
I need to either adopt Twilio's network (for free ideally) or more likely, start deploying more servers: south asia , australia, and South america are needed. Also LA would help
