### ISSUE TITLE
Suggestion: Push to talk

### ISSUE THREAD

**Issue by tenacioustechie** [steveseguin/obsninja#267]
Feel free to close this or point me to where I should make this suggestion. 

Fantastic tool, thanks so much for producing it!

I would like to suggest a push to talk button on the control centre screen (director view) this could be used to cue people in to be live. 

In our use case we use it to bring remote guests in, but our live stream also plays video content (church service) so it would be handy to count/cue the person in verbally from the control centre screen. 

Right now our work around is to join to room as well.

**Comment by steveseguin** [comment]
Hi tenacioustechie,

I've definitely received that request a few times now and also intend to add it. Thank you for making a git issue request for it.

Would you want the cue button to speak to everyone in the room? would you want to select which mic you use or just the default mic? would you need video?  do you want text chat ?

Last week I made some progress on making this feature request feasible, so it probably wouldn't be too much work now for me to add it in.

One temporary trick that you can use to have this work is to use one of my IFRAME demo apps to create two windows, opening one to the control room and the other to join the room as a participant. You can resize and move the windows around as needed then.

an image below is an example:
![image](https://user-images.githubusercontent.com/2575698/92068804-e0ff3680-ed75-11ea-9c59-a2a7c91a46d8.png)

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/92321241-6e50be00-eff6-11ea-8706-2a40687fe2f4.png)

Added to BETA; will be in production soon
