### ISSUE TITLE
Alternative Audio Loopback

### ISSUE THREAD

**Issue by timboxyz** [steveseguin/obsninja#312]
As well as the listed audio loopback systems. May I recommend 'blackhole' `https://github.com/ExistentialAudio/BlackHole` This works on Catalina which I don't think all the others do.

**Comment by steveseguin** [comment]
Thanks tim.  I've been using it the last week or so now and I'm slowly adding it to the documentation as an option.

https://github.com/steveseguin/obsninja/wiki/FAQ#how-to-capture-audio-on-mac

**Comment by timboxyz** [comment]
Great, I just noticed it wasn't there yesterday when I happened upon that page while looking for something else.

**Comment by steveseguin** [comment]
Totally. I much appreciate the comment and heads up with this new app. I've been updating much of the wiki tonight, so a bit of a coincidence I guess. 

Thank you,.
