### ISSUE TITLE
add ability to force hangup lingering guests as a director

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#338]
sometimes they forget to close their browsers
or they get 'jammed' and need to be manually removed? not sure how to do that, but at least hangup.

**Comment by steveseguin** [comment]
@ Yash1331

**Comment by Tenkir** [comment]
Just generally, it'd be a great help to be able to remove users as a director. Being able to kick users or otherwise have moderation controls beyond just muting a guest would make this tool much more useful in live production environments.

**Comment by steveseguin** [comment]
Added a basic version to the ALPHA version: https://obs.ninja/alpha/

I have some more work to do before it's ready, but I welcome some early feedback.

I've also been experimenting with a way of transferring select users from one room to another. A greenroom of sorts could be made this way.  More work needed here, too.
