### ISSUE TITLE
have the iFRAME API's mute button provide a callback of state

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#354]
jsofferToday at 4:11 PM
so this line
iframe.contentWindow.postMessage({"mute":"toggle"}, '*');
This is "Toggle Speaker"
steveToday at 4:12 PM
do you want a callback?
ok
jsofferToday at 4:12 PM
yeah i just need something to ensure that this happened
so i can make the button like change text/color etc

**Comment by jeffreylsoffer** [comment]
I think I'm actually fine without this steve. Sorry to bother!
