### ISSUE TITLE
mute button in group window doesn't mute director's PTT audio. intentional?

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#394]

**Comment by steveseguin** [comment]
accidentally.  not sure if I should change it or not.

**Comment by chrismarquardt** [comment]
I've thought a bit about this. Director has a special role, so I think guests should not be able to mute the director's audio.

**Comment by chrismarquardt** [comment]
clarified in v13, PTT audio overrides mute by definition ("voice-of-god"), closing
