### ISSUE TITLE
UI director's room: stray icon

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#395]
what is the black avatar icon next to the director's PTT button for?

**Comment by steveseguin** [comment]
this is a video tag.  It contains the audio/video media.  If you click settings, and select video input device, a small thumbnail will appear of your video or screenshare.

It's a bit hacky.  I was thinking of putting an audio meter here in place when it is audio-only.

**Comment by chrismarquardt** [comment]
[alpha] Duuuude, I didn't even realize that you could share your camera as a director, I always assumed it was audio only. Probably because of "push-to-TALK" ... I'm blind.

Now of course with the director not showing in the guest room, selecting the camera doesn't make much sense.. but I love the idea of guests being able to see the director when needed.

So hmm... would it be hard to dynamically add/remove the director from the guest view when PTT is enabled/disabled? Or would that generate too much visual clutter with the director showing/hiding and thus rearranging the guest view all the time?

I think the only way to tell how well that works is to see how this works in practice.

Added polish/consistency bonus: use the same placeholder icon like on the empty default guest boxes and make it smaller so it fits the box.

**Comment by chrismarquardt** [comment]
fixed in v13, closing (the avatar on the icon is still too big, but oh well, probably will open its own enhancement request for that)
