### ISSUE TITLE
UI director's room: padding around PTT button

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#404]
UI: add top/bottom padding to director's PTT button, for visual consistency it should be the same as around the link boxes and around the guest boxes. [polish, consistency]

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/96389284-b24deb80-117c-11eb-9b4c-799b3a2fe010.png)
 ??

**Comment by chrismarquardt** [comment]
Consistency and alignment! \o/ Thank you so much! Closing this
