### ISSUE TITLE
director's room: make arming consistent between transfer and recording buttons

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#406]
when a guest recording is armed, change text from 'selected' to 'armed' and change button color to #BF3F3F for clearer indication of armed-ness [polish, consistency]

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/96388410-9ba49600-1176-11eb-8bb8-4b633dfec64c.png)

added the consistency, but I wanted to use cross-bones for the hang-up icon when armed.  I didn't think the existing icon really indicated "death" and armed looked more like "Garmed" with the other icon.
