### ISSUE TITLE
director's room: different bitrates for different recordings? 

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#407]
when releasing CMD key after arming multiple recordings, the bitrate popup comes up repeatedly, once per selected video. would it make more sense to only pop this up once and record everything at the same bitrate? also, with multiple pop-ups it's not clear which popup belongs to which video (order of arming? display order?) [usability]

**Comment by steveseguin** [comment]
this was a bug. Fixed.  You can now select the bitrate when you let go of CTRL and it will ask for the bitrate; that bitrate will apply to all recordings.

I also increased the placeholder/default recording bitrate to around 4000-kbps.  This is more in-line with expectations for 720p talking head video I guess.  (4000kbps will produce closer to 3000-kbps results in reality I think, but whatever)
