### ISSUE TITLE
director's room suggestion: changes to background tint when guest is added to scene

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#409]
when "add to scene" is selected, the background green tone only has little contrast to the white buttons. suggestion: change the background green tone to #649166

also, would it be possible to green tint the entire guest box and not just the button box under the guest? 

alternatively don't tint the box at all, instead add a green border around the entire guest box? that would probably be my preference. this would still be visually clear but not disturb the overall UI as much. something like a 2 or 3px #649166 border should do the trick [nice to have, usability]

**Comment by steveseguin** [comment]
I have it changing the background color of the entire container to #649166 on dev now.

When I had it set the border color, it caused the container to change size.  I also felt like 2 or 3px wasn't enough substance; on my monitor it was still a very thin line.  I can resolve these issues perhaps, though for now I'll just stick with the background-color improvement.

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/96387300-04881000-116f-11eb-9f86-2241d2303c25.png)
![image](https://user-images.githubusercontent.com/2575698/96387307-15d11c80-116f-11eb-827e-48e96650d091.png)

**Comment by statik** [comment]
absolutely loving all this polish!

**Comment by chrismarquardt** [comment]
Tested on alpha, amazing looking!! I'll go ahead and close this.
