### ISSUE TITLE
StreamLabs for Mac has Framerate issues

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#43]
While Streamlabs OBS for MacOS works, with audio and obs Ninja, it does not do a good job with frame rates.

Really bad.  
Setting the resoltion to 640x360 helps, but it still is bad.

This seems to be a bug with CEF. and until that gets fixed, OBS on MacOS will be suffering.

**Comment by steveseguin** [comment]
lack of hardware acceleration it seems like

**Comment by Xartos** [comment]
I have issues with low framerate with obs-studio on a Linux machine. 
Could this be the same issue?

**Comment by steveseguin** [comment]
Lack of hardware acceleration is often the issue for low frame rates. Make sure you turn it on in OBS, make sure you have the correct graphics card drivers installed, and ideally make sure you are using a relatively newer version of OBS.

![image](https://user-images.githubusercontent.com/2575698/82059759-7a55f000-9694-11ea-91e3-79a6cb6759f9.png)

Can you can try different video codecs; see the wiki, but view=xxx&codec=h264 sometimes helps.

Also, I mainly support Chrome, so make sure the publisher is using Chrome and not something odd.

There is a linux support channel on the discord ; some other people have solved their low frame rate issues there.

**Comment by steveseguin** [comment]
Doesn't work at all currently on macOS for SLOBS.  either wait for an update , use OBS for macOS, use the Electron Capture app, or use PC.
