### ISSUE TITLE
wrong url triggers 'invalid characters' popup

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#432]
I omitted a ? and got the invalid characters popup

reproduce:
https://obs.ninja/director=blah

**Comment by steveseguin** [comment]
So the problem here is obs.ninja/XXXXX actually is the same as obs.ninja/?room=XXXXX

As per your request to alert users to me sanitizing a room or stream ID, the room name becomes "director_blah"

**Comment by chrismarquardt** [comment]
No change needed I guess, now that I understand what happens.

**Comment by steveseguin** [comment]
fixed on beta.  I'm attempting to 'auto-fix' common mistakes now when the error is a bit obvious and give more accurate messages when not so obvious.
