### ISSUE TITLE
Couple of niggles on the update

### ISSUE THREAD

**Issue by TrainDan** [steveseguin/obsninja#440]
Hi - Just a quick heads up - You've got a typo in the main control room landing page - Broacast instead of Broadcast.

Incidentally, I'm now having trouble with contributors joining the group room with old url invites. Although - unless I'm missing something! - the text of the url seems to be exactly the same as previously,

Dan

**Comment by steveseguin** [comment]
Sorry for the slow reply here -- can you possibly share with me in private the links you are using?

I pushed one update to fix an URL-related issue today; there might be others though.

**Comment by TrainDan** [comment]
Hi Steve – no problem.

This is the room control room
https://obs.ninja/?director=GWRLive

And this is the invite link I am sending. It appears to be exactly the same as the link I sent previously, but it was either taking people to a separate room or flashing a message saying the stream ID was already in use: https://obs.ninja/?room=GWRLive

Dan

**Comment by steveseguin** [comment]
I fixed the message with streamID already in use I believe.  That's on production for a couple days now.  sorry about that issue.

I think I recall us talking and we discussed why the links you were using weren't working.  &room=xx needs to be added to view any guest in a room, as a security measure to enable private room transfers.

If there is still a problem, please let me know and I'll re-open this issue.

**Comment by TrainDan** [comment]
Hi Steve – you have indeed, I used it for an Armistice Day Service broadcast earlier today. Thank you

Dan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
