### ISSUE TITLE
can't get stats window on &novideo&style=2

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#442]
triggering stats window with CMD/CTRL-leftclick doesn't work on &novideo guests when style=2 is present. works fine without style=2

**Comment by steveseguin** [comment]
I considered this more a feature request, haha..  There is also no volume control.   This is due to the fact this it isn't a video, but a canvas element.  Definitely more work to do on &style=N before it's baked.

**Comment by steveseguin** [comment]
For the time being, you can do &stats , which will show it by default.

It's going to be some time I think before I will have this working.  I'll need to make a custom UI for audio controls first.
