### ISSUE TITLE
electron app on mac shows orange border when in focus

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#444]
![orange](https://user-images.githubusercontent.com/2527608/97421263-9846a280-190c-11eb-8e93-94bc67baf37a.jpg)

i can provoke this with 1.0.9. / 1.1.0. / 1.1.1. by focusing away from the electron app and focusing back a couple of times. guess it's something server side? i assume it has to do with the tally light feature that is meant for the obs integration.

in case parameters have anything to do with it, here's the command line I used to open this instance (run in terminal):

open -a OBSN --args -t GUEST1 --width=1280 --height=720 --url "https://obs.ninja/?v=...&vb=2000&ab=162&codec=vp8&sink=..."

**Comment by steveseguin** [comment]
Thank you, Chris.  This is a new issue? or was this with v12 as well?

**Comment by chrismarquardt** [comment]
No obs involved, just electron on the screen. Never saw that before v13

**Comment by steveseguin** [comment]
this was fixed I think

**Comment by 27px** [comment]
Had the same issue in windows, this gets unnoticed in white/light background. this code in main CSS fixed it
```
:focus
{
  outline:unset;
}
```
