### ISSUE TITLE
When inside a room, the room's speaker mute button does not work.

### ISSUE THREAD

**Issue by vijay-howlround** [steveseguin/obsninja#491]
![mute button bug in a Room](https://user-images.githubusercontent.com/3924097/99188667-299a7f00-272b-11eb-9d10-9d44b85f30be.png)

https://obs.ninja/?room=[xxxxx]&push=[xxxxx]

**Comment by chrismarquardt** [comment]
The director’s voice (push to talk) is excluded from muting. The other participants should be muted
