### ISSUE TITLE
[beta] UI: Audio Sources pulldown in settings panel doesn't reset 

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#509]
Here's how to reproduce:

- start a push session
- open the settings panel
- click "Audio Sources" and select another audio input source
- dismiss the settings panel by clicking "Close Settings" or by clicking outside the panel
- open the settings panel
- click "Audio Sources" to change audio source

*expected behavior:*
audio sources pulldown opens on first click

*actual behavoir:*
audio sources pulldown resets on first click, but requires a second click to open

**Comment by steveseguin** [comment]
fixed
