### ISSUE TITLE
&webcam parameter dont ask for camera/mic permission #bug

### ISSUE THREAD

**Issue by 999999333** [steveseguin/obsninja#515]
Sending invite link with &webcam parametr leads to that browser didnt ask for camera permission, which leads to failure. 

Steps to reproduce:
1. Send invite link (eg. https://obs.ninja/?room=xxxx&hash=yyy&push=zzz **&webcam** ) to browser that never used OBSN (or for testing just set all permissions to default (ask).
2. Well after some loading it will eventually fail (as expected) **WITHOUT** asking for camera/mic permission

Comment: 
When I try it without &webcam it works as expected, browser dialog pops-up asking for permission. 
PS. &screenshare works ok

Tested on **Chrome v87, win 10**

![image](https://user-images.githubusercontent.com/4051127/100150585-1d878d80-2ea0-11eb-89e5-dc1f38661238.png)

**Comment by steveseguin** [comment]
Thank you. Adding the password request for some reason breaks things.  I'll look into this tonight

**Comment by steveseguin** [comment]
If possible, could you test https://obs.ninja/beta to see if it has fixed the issue?  thank you

**Comment by wakitcha** [comment]
Hi, I've experienced this issue as well.  (We add "&webcam&quality=2&hash=5c4e&audiodevice=0" to the share link.)  The beta site worked well for me.  Thank you!
