### ISSUE TITLE
allow guest to mute incoming video dynamically

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#549]
`Had a feature request from someone with low bandwidth asking if there was a way they could turn off incoming video feeds and just listen to people (like turning off your own camera if bandwidth is bad)`

**Comment by steveseguin** [comment]
just noting:  you can 'focus' on one video, and it will the other videos.  if you focus on your own video, it will probalby mute all the other without taking up bandwidth; just use the eye glasses in the top right of a video

**Comment by steveseguin** [comment]
added to alpha; https://obs.ninja/alpha
![image](https://user-images.githubusercontent.com/2575698/100887910-7f895980-3483-11eb-8ba7-b9808b2b01a6.png)

Setting slider to 0 will disable inbound videos.  Doesn't yet hide the videos elements if you do this, but it will stop the bandwidth usage

**Comment by chrismarquardt** [comment]
I'd simplify the way this works, my assumption is that most guests won't know or care and "why should I make the video I see worse in quality" - maybe a tooltip or question mark next to the slider with a popup explanation: "If you are on a slow network, you can make the other room members' video smoother by reducing the amount of video data that they send to you."
