### ISSUE TITLE
unhide the share screen from the settings panel

### ISSUE THREAD

**Issue by eazuka** [steveseguin/obsninja#575]
It will nice for the share screen feature to be unhide from the settings panel and brought as one of the icons beneath the video as part of icons in image below.

![image](https://user-images.githubusercontent.com/1465608/101273698-fed6a000-3797-11eb-829d-b3e2b5f8857a.png)

**Comment by steveseguin** [comment]
I added a button on beta for this, although you need to add a URL flag to enable it for now.

https://obs.ninja/beta/?ssb

The button is still a bit glitchy and not ready for it to be on by default.

**Comment by jcalado** [comment]
This is now actual production behavior!
Thanks for the feature request.
