### ISSUE TITLE
OBS on MacOS does not seem to work with OBS NINJA ATM

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#6]
GAH!
Prioriry

**Comment by steveseguin** [comment]
seems to be an issue with Chrome v75 on MacOS?

**Comment by steveseguin** [comment]
Solution for now is to download OBS v23 for Mac.

v24/v25 are broken. CEF bugs likely

**Comment by steveseguin** [comment]
A user reported that AUDIO does not work within OBS v23, but it did fix the webRTC issue ..
So this is NOT a fixed solution, as without audio that breaks things

**Comment by steveseguin** [comment]
StreamLABS is a solution, but it has a low frame rate.

Issue appears now to be that the OBS guys disable networking in the browser source due to another issue.

Frustrating.

**Comment by steveseguin** [comment]
Some users are mentioniong OBS v23 crashes on MAc.

**Comment by steveseguin** [comment]
If anyone is interested in testing this option out, I've had some success on my old Mac by using "Window Capture", but using the OBS.Ninja like within Chrome.  Some cropping is needed, but performance should be fairly good. 

![image](https://user-images.githubusercontent.com/2575698/79679452-12ff6a00-81d4-11ea-9a87-a1b30f73de77.png)


If anyone wants to confirm this method works for them also, please let me know.

**Comment by steveseguin** [comment]
If anyone is interested in testing this option out, I've had some success on my old Mac by using "Window Capture", but using the OBS.Ninja like within Chrome.  Some cropping is needed, but performance should be fairly good. 

 https://imgur.com/vdl7xtB 

If anyone wants to confirm this method works for them also, please let me know.

**Comment by VittorioParagallo** [comment]
well... it works, but it doesn't get the audio. so.. no way :..(

**Comment by steveseguin** [comment]
There are tools to capture audio on MacOS.  I have a list of them here, including free ones.

https://github.com/steveseguin/obsninja/wiki/FAQ#macaudio

**Comment by unknowndomain** [comment]
@steveseguin Why is this a no fix, reading online people are saying it didn't have this issue in the old version of obs.ninja, it's unclear what the fault is here?

**Comment by steveseguin** [comment]
The issues some are having with the "new" version of OBS Ninja and old are not related to the issue of OBS v24/v25 not working.

OBS v24/25 switched to a new version of Chrome Embedded Framework, which was designed to capture the audio from the Browser Source, etc. Unfortunately, that version of CEF does not support hardware video accelerated decoding on macOS yet.

The OBS team, in an attempt to fix another issue, decided to just disable WebRTC.  Even if it were enabled, the video frame rates would be very low.

https://github.com/obsproject/obs-browser/issues/209

If you would like to try it, the Streamlabs OBS beta for MacOS will work, but at low frame rates.

OBS v23 should work, although it crashes for many people on the new version of MacOS.

I've also released an Electron app for those looking to do "screen capturing" with newer versions of OBS Ninja.  https://github.com/steveseguin/electroncapture  I'll continue to improve that app over the coming weeks, as it still has some limitations.

Other users have had luck installing Bootcamp and Windows on their Macs.

**Comment by unknowndomain** [comment]
I'd be more comfortable with Windows tbh, so is it working at good frame rates on Windows?

**Comment by steveseguin** [comment]
It works quite well on Windows 10, with OBS v25.  Good frame rates and audio capture works.  There is also a virtual camera option, which MacOS lacks.

I'd also suggest people try the vp9 video codec, rather than the default browser-based one, if you run into any video artifacting.  OBS still seems to have a few issues with WebRTC

**Comment by steveseguin** [comment]
Just an update on this, as its been a while.  

![image](https://user-images.githubusercontent.com/2575698/99908975-b5745400-2cb3-11eb-99a5-cce82d973f74.png)

`10/30/2020
an update re: OBS and CEF.  This probably relates to everyone using OBS.Ninja.

- audio drift and even total audio failure may likely be an issue with the out-of-date version of CEF used in OBS. 
- the OBS crew is being forced to move forward on updating CEF 
- this might mean no video distortion, buffer support, and macOS support in the coming month`

**Comment by chrismarquardt** [comment]
Sorry, not sure I read that last sentence correctly. Does the "no" extend to buffer support and macOS support or should I rather read this "no video distortion, yes buffer support, yes macOS support"? If it's the latter, then 🍾

**Comment by steveseguin** [comment]
The latter, yeah.

OBS devs have nothing blocking them anymore; just hard work ahead.

I'm probably being optimistic, but numerous old issues could be fixed.

Apple of course with ARM has made things more complicated. We shall see.

**Comment by steveseguin** [comment]
No Longer an Issue !!  Latest OBS v26.1.2 supports macOS and OBS.Ninja!!
https://github.com/obsproject/obs-browser/issues/209#issuecomment-748683083
