### ISSUE TITLE
Feature: automatic detection of user going offline or back online

### ISSUE THREAD

**Issue by filiptronicek** [steveseguin/obsninja#601]
I would love to have a feature like that on OBSN, which could also use the `navigator.onLine` ([MDN spec](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine)) bolean to figure out if the user is offline or not.

The feature could look something like this: _(where `#offline-modal` would be a modal telling the user that the connection couldn't be made)_

```js

// The user going offline
window.addEventListener('offline', (_e) => { 
  document.getElementById("offline-modal").style.display = "block";
});


// The user coming back online
window.addEventListener('online', (_e) => { 
  document.getElementById("offline-modal").style.display = "none";
});
```

This modal could also be used to handle rejections to connect to the WebSocket server like:
`webrtc.js?ver=118:9 WebSocket connection to 'wss://wss13.obs.ninja/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED`

**Comment by jcalado** [comment]
As mentioned, #742 handles this.
