### ISSUE TITLE
Make director’s view of room customizable

### ISSUE THREAD

**Issue by 2xbass** [steveseguin/obsninja#603]
Is it possible to make the director’s view of a room customizable? For example there are currently three rows with:

a) invites at the top
b) a smaller row with a way to enable PTT and a documentation link
c) video views with browser source links

I’d like to just show c)

**Comment by steveseguin** [comment]
If I added a "collapse" button, that hides A, would that be helpful?

Or would you prefer I add a URL-parameter that hides A+B ?

**Comment by 2xbass** [comment]
Hi Steve, thanks for the super quick response. I would definitely prefer URL variables to hide various elements. I want to make it as simplistic as possible. Also being able to hide the chat and mute toggle buttons at the bottom would be great too.

**Comment by steveseguin** [comment]
Perfect.  Thank you for the feedback.  I can make that happen easily enough

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/102117890-e8ba8680-3e0c-11eb-98f1-8f9f8d93b33b.png)

Added &cleandirector , which hides the stuff you mentioned.

and you can further hide the mic, chat and header areas by adding &cleanoutput

I might have the camera PTT button added back in for &cleandirector, but hide it when &cleanoutput is added -- not sure yet..

Anyways, this code in on my local dev. I'll push it to alpha/beta a bit later on, and it will be in the next release.

**Comment by 2xbass** [comment]
You're a legend Steve. Thanks so much.

**Comment by 2xbass** [comment]
@steveseguin, just wanted to check: is the hiding of the mic and chat with &cleanoutput a new thing as part of this issue or should that already be happening in the current code? Right now if I do &cleanoutput with &director it does hide the header but not the mic and chat.

**Comment by steveseguin** [comment]
https://obs.ninja/alpha   You can try it out there.

&cleanoutput was updated on alpha, as it wasn't hiding the mic icons before.

I might fiddle with these things a bit still, but I wanted to hack something so you had something.

**Comment by 2xbass** [comment]
I can’t seem to make the chat and mic disappear on obs.ninja/alpha no matter what I do but it’s OK I’ll trust it’s working and also totally understanding you might still change it. I’m running my own server anyway and can clone the alpha branch when it’s there to test locally. Thanks again.

**Comment by 2xbass** [comment]
Working for me on alpha now. Looks great!
