### ISSUE TITLE
Possibility to change av-bitrate (mb codec?), aec, denoise, autogain on the fly

### ISSUE THREAD

**Issue by briggeml** [steveseguin/obsninja#606]
Is it subj possible without reconnection (like changing an av-source)? And what about metrics available through some JS API to monitor network quality suitable for implementation an custom algorithm for changing the connection params (bitrate etc) on the fly when the network quality are degrading?

**Comment by steveseguin** [comment]
on https://obs.ninja/alpha ; you can change the AEC/autogain/denoise and such on the fly, although it will cause the video to flicker.  See the Settings button and Advanced Audio.

There is an API available (IFRAME API) to monitor network stats of all connections.  You could access this by hosting OSB.NInja inside an IFRAME.  You can also control the bitrate dynamically I think with this API.  For example, this is what the speedtest does. https://obs.ninja/speedtest for example logic

The code already adjusts bitrate based on network quality degrading.
