### ISSUE TITLE
Enable PiP on iPhone

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#609]
So there usually is an option to go PiP when I watch streams of sports
On safari
But for full screen obsninja I can't do that

CallMeFilToday at 3:12 PM
Just myself atm. So I can have the screen recorded my gaming on my iPhone and sent to twitch @steve

**Comment by filiptronicek** [comment]
This would be great! Below are the docs I could find

https://developer.apple.com/documentation/webkitjs/adding_picture_in_picture_to_your_safari_media_controls

**Comment by jcalado** [comment]
This can be worked over on #800 .
