### ISSUE TITLE
possible XSS vulnerability in webrtc.js

### ISSUE THREAD

**Issue by fabianfreyer** [steveseguin/obsninja#618]
In `webrtc.js`, in the `receiveChannel`'s `onmessage` handler, the JSON message is deserialized into `_0x195255`.  Later, `_0x195255.info.label` is assigned to the label element's `innerHTML`.

**Comment by steveseguin** [comment]
This is the code being used in the receiveChannel's onMessage.
`if ("label" in msg.info){
	session.rpcs[UUID].label = msg.info.label;
	if (session.rpcs[UUID].label){
		session.rpcs[UUID].label = session.rpcs[UUID].label.replace(/[\W]+/g,"_").replace(/_/g, ' ');
		if (session.director){
			var labelID = getById("label_"+UUID);
			if (labelID){
				log(msg.info.label);
				labelID.innerHTML = session.rpcs[UUID].label;`
				


I don't think there is a flaw here after reviewing the code, but the use of innerHTML is still inappropriate of me. I'll go thru all the code and replace innerHTML with innerText where appropriate with to make double-sure though this isn't a problem elsewhere.

When doing some deeper XSS review this hour, I can see some other places where I can improve the code as well, so I'll spend time today doing that and it will be pushed with the next version 14 release coming soon.

There are peer to peer related issues that go beyond XSS though, as there are some fundamental commands that have one peer requesting another peer to do something, and if that peer refuses to obey, the system breaks. At such, OBS.Ninja is still largely trust-based, so it is recommended to only use it with trusted peers.
