### ISSUE TITLE
&ad + &autostart + &wc == noaudio?

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#623]
if I do ad command without the autostart and wc it will switch my audio source correctly.  However, when I use the ad command with autostart and wc, everything launches correct but the audio source shows "no audio".  If I replace the ad command with od, it works and switches the audio output and everything launches correct but I'm trying to switch the audio source.

**Comment by jcalado** [comment]
&autostart is enough to trigger this behavior.

I can replicate with &ad=Line&vd=0&autostart

**Comment by jcalado** [comment]
It seems this is fixed in /beta so will land in production soon enough.
Hurray Steve 👍
