### ISSUE TITLE
Stuck at loading camera #bug

### ISSUE THREAD

**Issue by 999999333** [steveseguin/obsninja#635]
Steps to reproduce:

When trying to connect with non-working or disconnected camera device (eg. disconnected ndi, random webcam drivers..) It is  stuck in loading screen/"is camera ok?" notification and selecting another source dont solve it.

Comments:
In previous version (eg. https://obs.ninja/v13) it works as expected... when selecting non-working source it tries to load it, but when you change it to working one it changes to the right one.

Video to better ilustrate bug, due to my language barrier.

https://user-images.githubusercontent.com/4051127/103140650-70e03c00-46e9-11eb-91d4-0b44df2a4625.mp4

**Comment by 999999333** [comment]
Quick workaround: Start with screensharing and then go and in video source select proper source.

**Comment by steveseguin** [comment]
I'll look into this. Thank you for the video and for reporting it; it helps a lot.  While I can get it working with an empty NDI device (I wrote code specifically for NDI to address this issue there), there might be problems with other devices, like the HD60 Pro.   I'll see if I can replicate.

Just in case also, if you haven't tried already, please make sure the browser cache has been cleared, as that fixed the issue for another user so far it seems.

**Comment by steveseguin** [comment]
I updated Production with some cached code.  Let me know if the issue has been fixed. Do a hard browser refresh before trying please.
