### ISSUE TITLE
Group Scene layout customization

### ISSUE THREAD

**Issue by chrisinhim** [steveseguin/obsninja#655]
Please allow the user to change the Group Scene layout from vertical  to horizontal and vice versa.

When I'm capturing the group scene in OBS, I'm getting the portrait mobile videos vertically. I want them to be side by side.

**Comment by steveseguin** [comment]
Thank you for the request.  I just added it for you.

![image](https://user-images.githubusercontent.com/2575698/104572919-49aec780-5622-11eb-85d6-10b562d81bae.png)

&portrait or &vertical or &916 will now enable this.

&square or &11 will trigger a 'square' window, also.

In the future, I'll provide a lot more control and have more intelligent mixing -- so this solution hopefully will only be needed temporarily.

You can test it on https://obs.ninja/beta
