### ISSUE TITLE
limit bitrate based on "window size" in OBS 

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#66]
limit bitrate based on "window size" in OBS

goal will be try to keep things cooler; no need in 10mbps if a 300px wide window.   Lots of CPU performance issues currently

lots of challenges with this, including spamming during resizing, and whether I should override the users's settings.

code to support this all  is present and ready to go --  just need to make sure it doesn't hurt the user's expcations.

**Comment by steveseguin** [comment]
Partially implemented.  Seems like the idea is valid too, as I can detect if the scene is active as well.

**Comment by jcalado** [comment]
This has been severely expanded upon by Steve and is now current behavior.
