### ISSUE TITLE
How to change the url of the TURN server in the client software

### ISSUE THREAD

**Issue by tim-cools** [steveseguin/obsninja#669]
Hi, I'm looking into hosting our own TURN server, and like to know how to change the url of the TURN server in the client. Is it just replacing the url in webrtc.js? Or is there a more maintainable way?

Also, the discord invite seems not valid anymore, is it still active?

Thanks for the support!

**Comment by jcalado** [comment]
Hi!

You can join the discord via http://discord.obs.ninja/

You can also set a turn server by setting the **&turn** URL parameter: https://github.com/steveseguin/obsninja/wiki/Advanced-Settings#-turnfalseoffusernamepasswordturnserveraddress

**Comment by steveseguin** [comment]
At the bottom of the index.html file, there are commented out lines.



            var session = WebRTC.Media; // session is a required global variable if configuring manually. Run before loading main.js but after webrtc.js.
			session.version = "15.3";
            session.streamID = session.generateStreamID(); // randomly generates a streamID for this session. You can set your own programmatically if needed
			
			session.defaultPassword = "someEncryptionKey123"; // Disabling improves compatibility and is helpful for debugging.
			session.salt = location.hostname; // used only if password is not == False.
			
            // session.configuration = {
            //    iceServers: [
            //         { urls: ["stun:stun.l.google.com:19302", "stun:stun4.l.google.com:19302"] }, // more than 4 stun+turn servers may cause issues
            //    ],
			//    sdpSemantics: 'unified-plan'
            // };

            // var turn = {};
            // turn.username = "steve";
            // turn.credential = "justtesting";
            // turn.urls = ["turn:turn.obs.ninja:443"]; // US CENTRAL
            // session.configuration.iceServers.push(turn);

            // turn = {};
            // turn.username = "steve";
            // turn.credential = "justtesting";
            // turn.urls = ["turn:turn2.obs.ninja:443"]; // US WEST
            // session.configuration.iceServers.push(turn);

**Comment by steveseguin** [comment]
I didn't mean to close this, but

**Comment by tim-cools** [comment]
Wow, great support! Manu thanks!
