### ISSUE TITLE
OBS v23 Crashes on MacOS

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#69]
Some have it crash on load; others on loading sources.

Newer versions obviously won't work.

**Comment by dodgepong** [comment]
23 and prior did not support 10.15 Catalina.

**Comment by steveseguin** [comment]
@dodgepong Thank you for that confirmation.  Oddly, my Mac Mini from 2012 (Intel 4000 iGPU) seems to handle it fine, minus what looks like a lack of hardware acceleration.

What options are available to those on Catalina wanting to do WebRTC video via OBS?  If this is the case, it doesn't seem like there are any good ones.

![image](https://user-images.githubusercontent.com/2575698/79670917-4ae6bd00-8194-11ea-8b4c-2a3fa6cfad23.png)

**Comment by dodgepong** [comment]
I don't know of any good ones, unfortunately. You could make a custom build of OBS for Mac that has NetworkService re-enabled in obs-browser, though it will have the same performance problems that Streamlabs has on Mac.

**Comment by steveseguin** [comment]
If anyone is interested in testing this option out, I've had 'some success' on my old Mac by using "Window Capture" and using the OBS.Ninja link within Chrome.  Some cropping is needed, but performance should be fairly good if it works.

![image](https://user-images.githubusercontent.com/2575698/79679458-30cccf00-81d4-11ea-9722-0e7478242455.png)

If anyone wants to confirm this method works for them also, please let me know.
