### ISSUE TITLE
Speedtest link missing .html in 16.2

### ISSUE THREAD

**Issue by doug86i** [steveseguin/obsninja#712]
Hey Steve,

Just updated our deployment to 16.2 and the speedtest link is:

onclick="window.location = './speedtest';"

I believe it should be:

onclick="window.location = './speedtest.html';"

Dx

**Comment by jcalado** [comment]
Hi!

I'm guessing this is because Steve has a rewrite rule on the site, so he can ditch the .html and make the urls cleaner.
This stems from the fact that the github release is the code that runs on obs.ninja and is tailored to that reality.

**Comment by doug86i** [comment]
Makes sense, however I feel it would be sensible to not rely on custom rewrite rules for the realeases IMO.

Dx

**Comment by steveseguin** [comment]
Thank you for the feedback, dough86i. I can understand your view.

I provide the required rewrite rules in the installation instructions:
https://github.com/steveseguin/obsninja/blob/master/install.md

Filenames are used by the app as shortcuts to room names, so there is some functional reason for it.  I haven't yet setup custom release workflows for the Github version, one for release and one for use by OBS.Ninja, but in time I may actually move in that direction.  At this point in time, the release version on Github simply mirrors the stable release version of OBS.Ninja.

I don't really think this particular case needs two versions to solve the problem though; I may add the filenames back in and just rely on some added code checks to make sure things are compatible.

**Comment by steveseguin** [comment]
I'm closing this issue as I've added the .html to the speedtest link.  My Nginx rewrite code handles it fine, so it's not an issue to add.  I'll push this code to github later on, but for now it's on beta: https://obs.ninja/beta/

thank you all.

**Comment by doug86i** [comment]
Thanks Steve, Please ignore if you don't feel it's important but the chat window popout function has the same issue.

main.js

window.open('./popout.html?id=' + randid, 'popup', 'width=600,height=480,toolbar=no,menubar=no,resizable=yes');

vs

window.open('./popout?id=' + randid, 'popup', 'width=600,height=480,toolbar=no,menubar=no,resizable=yes');

**Comment by steveseguin** [comment]
Thank you. Fixed on dev.  I'll update to github with my next update.
