### ISSUE TITLE
Stylize site to look nicer; also conslidate Style into a template

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#72]
-Make it easy for people to change the style without changing the function

-make the style its own files, so its easy to fork and yet remain up to date with master

-keep design unopinionated in tooling ; clean, simple

- I'm liking a cyberpunk theme giong forward; we shall see.

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/79670988-d1030380-8194-11ea-9f8c-c759a747b5a4.png)
https://github.com/dhaitz/mplcyberpunk/blob/master/img/demo.png

I'm liking this theme, but I would need to make sure it was not too 'extreme'.  Gentle colors also work better in OBS if the app crashes - I rather it crash to black than to Pink.

Still, I like it!

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/79671160-34d9fc00-8196-11ea-9cdb-747defd6a5b3.png)

Perhaps how it will go

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/81007619-8e415c80-8e1f-11ea-99fc-cdd40295c4ed.png)
Another user-generated example

**Comment by jochmann** [comment]
I'm on it (well, just directing the coding efforts): We'd like to use our own agnostic CSS-framework as much as possible (class-less CSS applied to semnatic HTML) and add a scss-module for OBS.ninja specific needs, where we have to use classes.

We may have to rearrange the HTML for this to work. Upside: The style becomes easily customizable via variables. Downside: Don't know if we break compatibility with upstream. Do you think this is a feasible approach for you to acceppt pull requests?

We'll create two index.html for our own purposes (we want to lower the barrier to entry for non-technical folks and remove all information about OBS in a super simplified start page for them) btw. One will mirror the original functionality though, to be hosted in a subfolder for advanced users.

Any requirements you would have us meet for you to be able to use our contribution?

**Comment by jochmann** [comment]
> I'm liking this theme, but I would need to make sure it was not too 'extreme'. Gentle colors also work better in OBS if the app crashes - I rather it crash to black than to Pink.

How about setting backgrounds to transparent on default and have only the relevant divs and the error message render on a background so that it looks like a floating card in OBS? Can easily be exposed to the OBS-browser where in the CSS you overwrite standard styles

```
foo {backgorund:none !important;}
```

I'm loving obs.ninja precisely because it fits into to my growing web-app-ecosystem of overlaying obs-browser instances with custom transparency settings. It's starting to look like minority report on my screen 🤣

**Comment by steveseguin** [comment]
I'm very slowly separating the style from the function; you might beat me to that in some ways.  Regardless of what I do, I don't think I'll please everyone in the end. I am definitely open to PR-requests.  

I acknowledge that my code is rough, but it's also allowed me to rapidly design and hack out features. As things progress, I'm able to slow down more and consider how I want things organized.  Historically when working with other developers, I find myself eventually 'locked out' of the development process by an overzealous expansion of process and dependencies and frameworks. I get a bit tense working with other developers as a result.

Simplicity is important to me.  I do need to remind myself of that as time goes on, but that is a design goal. I have a lot of code-debt currently; I know I am going to need to reorganize many parts of the code base at some point. I'm doing so as needed; cleaning up code when intending to add complexity.

Mobile-first is a design goal as well. I'm not 100% sure I'm meeting that goal currently, but I'm getting there. There are some rough edges on Mobile; having the mobile experience feel like a native app experience would be fantastic. 

I don't want to be bogged down in development at this point by needing to support things like other languages and multiple versions of the code. I would be prepared though to make a few fixes to the codebase to make it more compatible with forked versions and I'd be prepared to try to develop the code in a way that respects that separation.

I'd probably suggest changes to the code base be made in baby steps. For example, the Main.js and webrtc.js files are injecting HTML code into the index.html file in places, in a bit of a hacky-template sort of way -- I do see there being room here; maybe instead of writing directly to the DOM with my Javascript code , I could write to a redux-like state database instead. That could become an API-layer for my javascript-layer to talk to.  If that state-store system replaced a small part of the app at first, I could adjust to those changes before proceeding to replace other parts of the UI-Javascript interface. 

A large PR request will simply overwhelm me I feel.  I've worked with exceptional front-end designers and mediocre ones; I would be willing to let an exceptional engineer make larger PR requests if they were able to respect some of the odd aspects of my coding preferences. 

Off the top of my head, so far I've been having fun with the follow design goals

-I've isolated the jquery calls to a dedicated file; I generally dislike Jquery.
-I've avoided bootstrap.js and other frameworks; I'm mainly using native HTML functions
-I avoid dependencies whenever I can, with a few adapter-exceptions.
-I've generally been doing a single-page design.
-I've avoided cookies and anything that might be considered tracking code
-I dislike working with React.js
-I dislike having hundreds of micro-sized files, including images. I've been particular about the ones I have added.
-I dislike compiling code; webpacks and such.
-zero data collection

**Comment by steveseguin** [comment]
> > I'm liking this theme, but I would need to make sure it was not too 'extreme'. Gentle colors also work better in OBS if the app crashes - I rather it crash to black than to Pink.
> 
> How about setting backgrounds to transparent on default and have only the relevant divs and the error message render on a background so that it looks like a floating card in OBS? Can easily be exposed to the OBS-browser where in the CSS you overwrite standard styles
> 
> ```
> foo {backgorund:none !important;}
> ```
> 
> I'm loving obs.ninja precisely because it fits into to my growing web-app-ecosystem of overlaying obs-browser instances with custom transparency settings. It's starting to look like minority report on my screen 🤣

I have the beta-branch 99% up to date currently; https://obs.ninja/beta  I've removed some of the errors in OBS recently, including the QR code, as they were security hazards revealing stream ID's.

I do like the idea of minimizing errors and other aspects within OBS. If an error occurs, it needs to be handled gracefully and in a minimally disruptive way.  Initially I moved forward on the premise of UX-first, but with so many professionals using the app now, I've had to remove things like the QR code.

I thought the background was transparent already? At least the view-links.   

I'm indifferent about maintaining a 'blank' version of OBS.Ninja at present.  I can see it being useful as a 'unit test' of sorts for me, or a reference page to spec against. It is more work to maintain, and at present there are greater priorities for me, but if it was done well I'd adopt it quite openly and I'd welcome PR's to it.

**Comment by jochmann** [comment]
I think we can relate to most, if not all of these design goals. In that respect we may be quirky and perhaps even more opinionated in trying to create agnostic designs. Don't think we are exceptional in any other popular meaning of the word when it comes to front-end design.

We'll try to be respectful of your preferences and then we'll see how it goes and if it looks promising, we'll send a pull request. Thanks!


> -I've isolated the jquery calls to a dedicated file; I generally dislike Jquery.
> -I've avoided bootstrap.js and other frameworks; I'm mainly using native HTML functions
> -I avoid dependencies whenever I can, with a few adapter-exceptions.
> -I've generally been doing a single-page design.
> -I've avoided cookies and anything that might be considered tracking code
> -I dislike working with React.js
> -I dislike having hundreds of micro-sized files, including images. I've been particular about the ones I have added.
> -I dislike compiling code; webpacks and such.
> -zero data collection

**Comment by steveseguin** [comment]
I've shifted most if not all the main CSS and templates to the index , main.js, and css style sheet. 

I'll continue to improve and organize the CSS / templates / styles, but it will be done piecewise as needed.  I'm not too keen in adopting third-party frameworks or design philosophies at this time; I'm pretty happy with the approach I'm taking currently as it works well for me personally.  That could change if I no longer am a solo developer on this project, where I need to cooperate, but I can rapid develop as is this way,
