### ISSUE TITLE
Records always in Opus 128kbit stereo (64kbit mono) even if connection stats shows 256kbit or more

### ISSUE THREAD

**Issue by briggeml** [steveseguin/obsninja#763]
Tried different combinations &record or &record=6000 with or without &bitrate=0

Win10, Chrome 88.0.4324.190 (Official build), (64 bit)

**Comment by steveseguin** [comment]
Chrome won't let me record OPUS audio higher than around 130-kbps.  It will let me record lower though.  128-kbps OPUS is pretty high, but I can try adding PCM support to the video mode -- it just complicates things.

**Comment by briggeml** [comment]
That's great. If it were possible to record PCM in video instead of OPUS, that would solve the problem.
