### ISSUE TITLE
No PCM audio in records in any mode with &record &record=6000 with or without &bitrate=0 etc

### ISSUE THREAD

**Issue by briggeml** [steveseguin/obsninja#764]
Win10, Chrome 88.0.4324.190 (Official build), (64 bit)

**Comment by steveseguin** [comment]
Can you please confirm it works if you try &record=0

It will record as Audio-only in this case.

I have not yet added PCM support when recording video also.  Would you like that as a feature?

**Comment by briggeml** [comment]
Additionaly, disable video in video source, doesn't work with such urls: 

&vb=0&ab=510&buffer=0&sync=0&s&codec=vp8&q=0&fps=25&record=0
&vb=0&ab=510&buffer=0&sync=0&s&codec=vp8&q=0&fps=25&&record=6000
&vb=0&ab=510&buffer=0&sync=0&s&codec=vp8&q=0&fps=25&&record
&bitrate=0&ab=510&buffer=0&sync=0&s&codec=vp8&q=0&fps=25&record=0
&bitrate=0&ab=510&buffer=0&sync=0&s&codec=vp8&q=0&fps=25&&record=6000
&bitrate=0&ab=510&buffer=0&sync=0&s&codec=vp8&q=0&fps=25&&record
&bitrate=3000&ab=510&buffer=0&sync=0&s&codec=vp8&q=0&fps=25&record=0
&bitrate=3000&ab=510&buffer=0&sync=0&s&codec=vp8&q=0&fps=25&&record=6000
&bitrate=3000&ab=510&buffer=0&sync=0&s&codec=vp8&q=0&fps=25&&record

PCM support for recording both video and audio is what I wanted to have originally, unfortunately audio-only is not enough, and at the post-production always better to have a HQ-source

**Comment by steveseguin** [comment]
&vd=0 will disable video.

&vb=0 and &bitrate=0 is not intended to disable video.

I will try to add PCM to video.  I'm not sure how compatible the video will be with the PCM, but I'll give it a go.

**Comment by briggeml** [comment]
In Advanced settings from Wiki:
"If the bitrate is set to 0, no video will be recorded and the audio will try to be recorded as a 32bit PCM lossless file."
Nothing about videodevice=0. I disable video manually, with no result.
Still no luck with:
bitrate=0&ab=510&buffer=0&sync=0&s&codec=vp8&q=0&fps=25&record=0&vd=0
bitrate=0&ab=510&buffer=0&sync=0&s&codec=vp8&q=0&fps=25&record&vd=0
ab=510&buffer=0&sync=0&s&codec=vp8&q=0&fps=25&record=0&vd=0
ab=510&buffer=0&sync=0&s&codec=vp8&q=0&fps=25&record&vd=0

**Comment by steveseguin** [comment]
I've added the flag &pcm as a URL flag that will record audio as PCM when recording video.

This is on obs.ninja/beta 

I will push to production with the new release.

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/109408950-5ed68000-795c-11eb-89e6-b71a177ae994.png)

**Comment by briggeml** [comment]
Great news! But why does it transcode to h264 even if original video stream was in vp8/vp9? Wouldn't that be an overhead on weak configurations?

**Comment by steveseguin** [comment]
Chrome will not let me dump the video "as is". It *forces* me to transcode the video, so it doesn't matter so much what format it is saved as.. H264 is often hardware-encoded though, so h264 is the most likely to need the least amount of CPU.  I save the video at a slightly higher bitrate than what it was received as, in attempt to reduce quality loss. 

I will eventually make a desktop app that will allow for raw dumping of video.
