### ISSUE TITLE
Transferring guests and keeping set parameters?

### ISSUE THREAD

**Issue by DachsbauTV** [steveseguin/obsninja#780]
Hi Steve,

Is there a way to transfer guests from one room to another and keep their seit parameters from the invite link from the 1st room?

E.g. If i set &cleanoutput &q in my cue-room (and the invite links) and transfer the guest to my programm-room the guests video feed will still be clean and high quality?

Thanks,
Fred

**Comment by steveseguin** [comment]
The settings should transfer.  A feature request I'm working on is actually being able to offer the opposite -- transfer a guest and have different settings apply.

**Comment by DachsbauTV** [comment]
oh okay my bad. Sorry :)
