### ISSUE TITLE
Add director pan/tilt/zoom controls

### ISSUE THREAD

**Issue by TimPeterson** [steveseguin/obsninja#784]
Often cameras that can't physically pan or tilt still support PTZ controls. This would be particularly useful for models like the [HuddleCamHD Pro](https://huddlecamhd.com/pro/) which has a wide angle lens and a 4K sensor.

https://web.dev/camera-pan-tilt-zoom/

**Comment by steveseguin** [comment]
Hi Tim,

If the camera supports Pan or Tilt via the browser, those settings should be available already (via settings for both user and director)

Here's a page that can display the options available of different (connected) cameras:
https://obs.ninja/supports

![image](https://user-images.githubusercontent.com/2575698/111374589-ac006480-8673-11eb-8e88-6ae1006b2947.png)

I don't have a camera that has pan/tilt, but I've confirmed Zoom works

**Comment by steveseguin** [comment]
nevermind.  I read your post closer. You want pan/tilt even without a compatible camera.  Okay. I'll see what I can do

**Comment by TimPeterson** [comment]
I do want access to actual camera controls. The particular benefit of this with the HuddleCamHD is that I can request a 720p signal from the camera and then have it scale an arbitrary region from the sensor to actually send back over USB, rather than pulling the full 4K and cropping it in software.

Now that I look closer, it seems that the issue is that those controls are inconsistently accessible through Chrome. I have a laptop with integrated camera, a Logitech USB camera, and a HuddleCamHD, and I can bring all of them into OBS as a video capture input, go to "Configure Video," and get pan/tilt/zoom sliders that work. Yet none of them show PTZ controls as supported within OBSN. However, if I go to chrome://media-internals/ it does show pan-tilt-zoom listed for all three of them.

I do know that the USB UVC protocol supports both absolute and relative positioning modes for the PTZ controls, and it's up to the camera which version it supports. Perhaps Chrome only supports one kind?

In the absence of hardware-supported PTZ controls, software emulation would be great too.

**Comment by steveseguin** [comment]
The hardware controls I present via Chrome already, yeah, but the ones you linked to seem like they might be software.  I can try to use the software based ones if the hardware based ones are not available.

I do have a PTZ camera, but it's from like 2002, and I doubt it will work -- I also have a logitech BRIO 4K -- haven't tried it yet, but maybe it will work. From memory, I don't think it was available outside the driver, but dunno

**Comment by TimPeterson** [comment]
I'm pretty sure OBSN is somehow missing the fact that these settings are in fact supported. Your "supports" page doesn't show my camera as supporting PTZ, but Chrome itself does, and I was able to get it working on https://ptz.glitch.me/ . Depending on the specific camera's capabilities it may not always look like it's working at first, but with a little tweaking I was able to demonstrate that it works on that site just like it does within my desktop OBS. In my case, I have a Logitech C920, which has a native sensor resolution of 2304x1536. This hardware is only able to scale pixels down, so if you open the device with default settings you'll get full resolution and therefore no zoom ability. If I change it to call ``getUserMedia({ video: { zoom: true, height: 720, width: 1280 } })`` then I can zoom in up to 180% before it bottoms out at 1:1 pixels, as well as pan-tilt around that window. I would be surprised if your Logitech doesn't work the same way.

**Comment by steveseguin** [comment]
I've pulled out my logitech and confirmed it works here: https://webrtc.github.io/samples/src/content/getusermedia/pan-tilt-zoom/  but not in OBS.Ninja.  They are both using similar code though, so i'll start looking into out why it's not working.

thank you

**Comment by steveseguin** [comment]
okay, I found the issue and addressed it I think.

A few caveats. 

1.  You will need to add &ptz to the URL of the guest to have it be enabled. 
2. You need to accept the popup about "controlling the camera"
![image](https://user-images.githubusercontent.com/2575698/111395478-4cb24c80-8693-11eb-9d14-56834989860e.png)
3. You need to be using Chromium (chrome, etc); nothing too old either.
4. Your camera still needs to support it.

I'll post my changes to beta later tonight, but it is working after I included pan,zoom,tilt = true to the camera request screen.

Zoom will work with Android devices automatically it seems, without needing these extra permissions. Overall, I'm pretty confused.

**Comment by TimPeterson** [comment]
It's working well for me. Thanks!

**Comment by jcalado** [comment]
This is now in production as well. Thanks for the feedback, @TimPeterson
