### ISSUE TITLE
Audio distortion (xruns/clipping?) from 48k 16bit NDI source that is clean when monitored using other software

### ISSUE THREAD

**Issue by adempewolff** [steveseguin/obsninja#811]
Hi,

I have a camera and mic sending video and audio over hdmi to a [Magewell Convert HDMI TX](http://www.magewell.com/products/pro-convert-hdmi-tx), which is thenconnected to the computer running OBS ninja over a gigabit LAN.  On my computer I am using NDI Virtual Input to expose the NDI video and audio sources to the browser running OBS ninja.  The problem I am encountering is that while the video feed works well, the audio has constant distortion: crackling/clicking whenever the person speaks (I can't quite tell whether it is buffer issues, digital clipping or something else).  I encounter this problem with the audio whether I am a host or guest, and whether I am using Firefox or Chrome to run OBS ninja.

The same NDI audio feed has no distortion when monitored using NDI Studio Monitor or Vmix.  Further, if I run the audio into Vmix, then use NDI Virtual input to route the master output of Vmix into OBS ninja, the audio is clean with no distortion.

I'm guessing that there is something about the raw NDI audio feed that OBS ninja cannot handle well (the bit depth maybe? or a specific codec?), but I don't fully understand what OBS ninja is expecting from audio sources, other than a 48k sample rate.

Thanks in advance for any suggestions, and would be happy to provide any additional info that might be helpful.

**Comment by steveseguin** [comment]
OBS.Ninja is expecting 48000 sample rate, but it will probably convert to something else.

If you feed the NDI signal into this site, https://webrtc.github.io/samples/src/content/devices/input-output/ , while wearing headphones I guess to avoid feedback issues, see if it crackles also.

You can try add &noap to the OBS.Ninja push link to disable any audio processing; this might help reduce issues if it's a buffering issue.

If you select the NDI source, and unmute the local video preview, does that sound distorted? or only after it has been transmitted?

**Comment by adempewolff** [comment]
The webrtc tester has the same issue.  Also, since posting, I noticed that Vmix or even Windows Voice Recorder also has the same distortion when I use the virtual audio source created by NDI virtual input (versus having Vmix using the NDI source directly).  Accordingly, I am suspecting that this is an issue with either NDI Virtual Input, or something somewhere in the Windows Audio Architecture.

Interestingly, the flag `&noap` appears to consistently reduce the amount of distortion, however it does not completely eliminate it.

> If you select the NDI source, and unmute the local video preview, does that sound distorted? or only after it has been transmitted?

I'm not sure I'm following what you are suggesting.  That said, I am now pretty sure that this is not an OBS ninja problem, given that I can replicate it when monitoring using other software.  It's probably safe to close this issue as irrelevant to this project--unless you feel otherwise.

**Comment by steveseguin** [comment]
Sounds good.  If there are ways to increase the NDI buffer, if there is one, that might help potentially. Or changing sample rates / bit depth. Good luck
