### ISSUE TITLE
iFrame API see when a camera is turned off

### ISSUE THREAD

**Issue by Vicken52** [steveseguin/obsninja#819]
Is there a way to see if a camera has been turned off through the `getStats` api call or another call or an event that I can listen to?

Currently I've been using `getStats` and the `Requested_resolution` as a way of determining if a camera is enabled, but that value does not update when a camera is turned off.

I want to be able to dynamically add or remove cameras as they turn on and off in a overlay, but right now I would have to close the entire iframe and reopen it each time to get the `Requested_resolution` value to clear when it's turned off.

**Comment by steveseguin** [comment]
Hi Vicken,

you want to tell if a video in a scene was enabled/disabled? or do you want to tell if the user has muted their own camera?

I'll try to add something explicit either way

**Comment by Vicken52** [comment]
I want to see if someone muted their camera

**Comment by steveseguin** [comment]
I added some explicit events to the IFRAME API; they are on beta .  https://obs.ninja/beta

 mic-mute-state = true or false
 video-mute-state = true or false

to test, try : https://obs.ninja/beta/iframe
![image](https://user-images.githubusercontent.com/2575698/113384810-daa95b00-9354-11eb-894f-fb3a24b024a1.png)

**Comment by steveseguin** [comment]
I'm closing this it should be available soon on production, after beta finishes its testing
