### ISSUE TITLE
Best way to add a Virtual cam output to OBS on Mac OS?

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#82]
I don't know of a good solution here, as OBS VirtualCam is for PC only.

I've heard of recommendations of MacOS, but haven't test any.

anyone have suggestions that are tested? Maybe we can create a guide with links on how to set this up.

**Comment by dodgepong** [comment]
There is a plugin in development now, but not really ready for widespread use yet.

**Comment by steveseguin** [comment]
http://camtwiststudio.com/download/

This is what I've seen others use so far for MacOS.  

> Choose Desktop+ and press Select.
> In the Settings section choose Confine to Application Window

Might not be the best way of doing it, but maybe this would work for some crude applications.

**Comment by unknowndomain** [comment]
CamTwistStudio is basically dead I wouldn't recommend installing it on newer versions of macOS I've seen people really struggle to use their computer properly after.

**Comment by KovalevArtem** [comment]
https://github.com/steveseguin/obsninja/issues/82

**Comment by unknowndomain** [comment]
Eventually this might be production ready: https://github.com/johnboiles/obs-mac-virtualcam

**Comment by KovalevArtem** [comment]
> If anyone knows how to do a virtual cam on mac, and can include it in such an app, that would make it more of a priority to me

_Originally posted by @steveseguin in https://github.com/steveseguin/obsninja/issues/91#issuecomment-618531887_

@steveseguin Check out these links. A lot of people are interested in solving this issue ...
https://github.com/obsproject/obs-studio/issues/2568
https://github.com/obsproject/rfcs/pull/15

**Comment by KovalevArtem** [comment]
😔

**Comment by steveseguin** [comment]
@KovalevArtem If you would like me to re-open this, I'm happy to.  I thought the solution was already given tho --  I've validated that the JohnBoiles VirtualCam works for MacOS and OBS.Ninja.

https://github.com/johnboiles/obs-mac-virtualcam

Screenshot of it working
![image](https://user-images.githubusercontent.com/2575698/98462027-f8480f00-217e-11eb-8c65-93a252028600.png)

It might also be possible to use NDI Virtual Input as a webcam; though I haven't tried that.
