### ISSUE TITLE
OSBN should show a "video muted" icon for guests that disable their camera

### ISSUE THREAD

**Issue by CyBeRoni** [steveseguin/obsninja#850]
Just like for muted audio, if the guest's video is visible when it is disabled (like in director), it would be nice to have a visual indicator that the guest has used the mute video button and isn't having technical issues.

**Comment by steveseguin** [comment]
@CyBeRoni  I need more information on where this is a problem;

In v17, there's something for this already:
![image](https://user-images.githubusercontent.com/2575698/116647424-7d4efc80-a948-11eb-988e-47675bb35425.png)

is this request specific to the director's room? as it will just show a black screen when the video is muted currently there

**Comment by CyBeRoni** [comment]
> is this request specific to the director's room? as it will just show a black screen when the video is muted currently there

In the director's room there's no immediately discernible difference to me between someone having pressed the 'video mute' button, their camera being broken or I suppose possibly something having gone wrong with the connection. And this holds true for the room view too if the setting to show non-visible guests is enabled.

At this point if a guest shows up as a black screen for me (the director) then I have to assume they used video mute; it would be nice to *know* this.

**Comment by steveseguin** [comment]
Thank you for that feedback.  I'll see about adding some feedback for the director so they will know the video is muted.

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/116652107-7f1dbd80-a952-11eb-9c6f-801342571025.png)
I'll update alpha later today with this

**Comment by CyBeRoni** [comment]
Perfect! Thank you.
