### ISSUE TITLE
OBS.Ninja desktop application powered by Electron

### ISSUE THREAD

**Issue by KovalevArtem** [steveseguin/obsninja#91]
Desktop application for OBS.Ninja built with [Electron](https://www.electronjs.org/).

**Comment by steveseguin** [comment]
I've definitely been considering it.   If anyone knows how to do a virtual cam on mac, and can include it in such an app, that would make it more of a priority to me

**Comment by steveseguin** [comment]
https://github.com/steveseguin/obsninja/issues/79
