### ISSUE TITLE
The big difference in the way the video is broadcast

### ISSUE THREAD

**Issue by KovalevArtem** [steveseguin/obsninja#96]
### iPad:
![Demo](https://user-images.githubusercontent.com/36500228/80242905-d5d12700-866e-11ea-94e2-c576d2e06b09.png)
_(From the left)_ Maximize page zoom in browser on iPad
_(On right)_ Not the maximum page approximation in the browser on the iPad (with a much better image).
_(Screenshot of the clock is a small part of the scene)_

### PC:
**(From the left)**
![image](https://user-images.githubusercontent.com/36500228/80242222-b1287f80-866d-11ea-91ff-ba62a5dbf49a.png)
OBS.Ninja (Remote Screenshare into OBS)

**(On right)**
![image](https://user-images.githubusercontent.com/36500228/80242359-ecc34980-866d-11ea-97b9-9c4578972593.png)
Settings:
![image](https://user-images.githubusercontent.com/36500228/80242426-006eb000-866e-11ea-9d53-dc508f030ac9.png)
OBS + OBS-VirtualCam + OBS.Ninja (Add your Camera to OBS)

Why is there such a big difference?

**Comment by steveseguin** [comment]
I'm having a bit of a hard time following, despite the photos.

The screen capture in OBS Ninja tries to capture at 1280x720.
The camera capture in OBS Ninja tries to capture also at 1280x720 (unless changed)

The video constraints for the screen capture are:

> video: {width: 1280, height: 720, cursor: "never", mediaSource: "browser"}

I would imagine that OBS VirtualCam does not do a good job scaling video, so if you capture from the camera at 720p, add it to OBS at 1080p, and then use the VirtualCam at 360p,  the quality will be pretty bad.  I might suggest to have the OBS canvas be the same size as the resolution you want the VirtualCam to be, so it does not need to do any image resizing.

Did I misunderstand the problem?

**Comment by steveseguin** [comment]
If you are having problems with video quality, you can also try increasing the bitrate.  **&bitrate=10000** might improve the quality.

**Comment by jcalado** [comment]
Maybe this is a wontfix.
As I understand it the issue was with low zoom video quality fed from OBS Virtualcam.

This is on Zoom, not a fault of OBS / OBSNinja.
