### ISSUE TITLE
Clickable URLs in chat

### ISSUE THREAD

**Issue by cgeoga** [steveseguin/obsninja#974]
Hello,

Thanks for making this incredible software and hosting it for people to use. I have looked through the docs and the issues here but there is a chance this information is available and I've just missed it. If so, I apologize.

When sharing a URL in a chat message, is there any way to make it directly clickable? I am interested to try and use this platform with some less computer-savvy people, and I think it might be challenging if I asked them to highlight the link and then paste it into a new browser tab or something. But I am confident that they understand how to directly click on a link that shows up in a chat window.

**Comment by steveseguin** [comment]
Thank you for the request. I'll add it in.

**Comment by cgeoga** [comment]
Amazing, thank you so much!

**Comment by steveseguin** [comment]
If using https://vdo.ninja/alpha/ , the chat there now supports links; feel free to use or test from there for now

It will end up on github and/or on vdo.ninja/beta/ in the near future after some more testing

**Comment by cgeoga** [comment]
That is seriously amazing. Thank you again!
