### ISSUE TITLE
Can we translate for specific countries? e.g. "pt-br"

### ISSUE THREAD

**Issue by lguima** [steveseguin/obsninja#980]
Hi there, this is an awsome project! I'm looking forward to try out and contribute.

I'd like to know if it only supports generic translation per language ("pt") or if we can create a translation for a specific country ("pt-br")?

And if we can, how should be the filename pattern?

Thanks!

**Comment by steveseguin** [comment]
Hey Iguima, 

Feel free to just copy this file, edit with your translation, and then upload it to the translations folder under a new name.

https://raw.githubusercontent.com/steveseguin/vdo.ninja/develop/translations/pt.json

pt-br.json works.

Once submitted, I'll add it to the production release of the app and give it a name that you can select from the pop up menu.

If there's a specific name you'd want it listed as in the menu, let me know.

Thank you kindly

**Comment by lguima** [comment]
Awesome, thanks for answering, I'll do it!

Btw, maybe the language title could be placed in its own language, like Facebook does, for example:

![language-options](https://user-images.githubusercontent.com/1562097/186549840-94083e7f-ff51-4ad0-ade3-5c9106f10166.png)
