### ISSUE TITLE
rtc.ninja website text remove

### ISSUE THREAD

**Issue by Swiftgti** [steveseguin/obsninja#982]
Hi, Its possible to take out the legend in rtc.ninja website, when using the Share your screen option, in the main windows where you have to selecte audio inputs and press the "Select Screen to Share" button, at the bottom appears the legend with text:

For application-specific audio capture, [see here] 
(That goes to the web site: https://docs.vdo.ninja/audio)

Thanks!!

**Comment by steveseguin** [comment]
done
