### ISSUE TITLE
Can't change language on Self Hosted

### ISSUE THREAD

**Issue by MauricioOnetto** [steveseguin/obsninja#987]
Hello
Thanks for your great work
I've installed over Debian 11, Nginx, using Cerbot for SSL
Everything works fine but I can't change language
I tryed from the website button and also replacing "blank" by "es" from index.html
Thanks for your help

**Comment by steveseguin** [comment]
At the bottom of the index.html file, make sure to update the main.js import call to include  _data-translation="es"_

```
		// session.apiserver = "wss://api.vdo.ninja:443"; // specifiy a custom websocket API URL.
			// session.darkmode = false; // enable or disable the dark style theme as the default
			// session.defaultBackgroundImages = ["./media/bg_sample1.webp", "./media/bg_sample2.webp"]; // for &effects=5 (virtual backgrounds)
		</script>
		<script type="text/javascript" crossorigin="anonymous" src="./thirdparty/aes.js"></script>
		<script type="text/javascript" crossorigin="anonymous" id="lib-js" src="./lib.js?ver=434"></script>
		
		<script type="text/javascript" id="main-js" src="./main.js" data-translation="es"></script>
	</body>
</html>
```

![image](https://user-images.githubusercontent.com/2575698/188308337-e05269fd-b943-40b9-9a9c-899fec99725e.png)


If this doesn't work, make sure the es.json file is accessible at **youdomain.com/translations/es.json**   if that doesn't work, then you have a webserver issue.

You can also share a link to the hosted site, and I can take a look -- but I just tested things here on my instance, and it works for me.

** EDIT:

Note that in the screen shot, I think I accidentally included main.js twice.  It just needs to be added once, but using data-translation="es"

**Comment by MauricioOnetto** [comment]
Thank you for your answer

My website
https://v1.aulaholistica.com/

You're right translations/es.json is not accessible (error 500)

It is my nginx conf

`server {

	root /var/www/v1.aulaholistica.com;

	index index.html index.htm index.nginx-debian.html;

	server_name v1.aulaholistica.com;

        location ~ ^/([^/]+)/([^/?]+)$ {
                root /var/www/html/vdo.ninja;
                try_files /$1/$2 /$1/$2.html /$1/$2/ /$2 /$2/ /$1/index.html;
                add_header Access-Control-Allow-Origin *;
        }

        location / {
                if ($request_uri ~ ^/(.*)\.html$) {
                        return 302 /$1;
                }
                try_files $uri $uri.html $uri/ /index.html;
                add_header Access-Control-Allow-Origin *;
        }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/v1.aulaholistica.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/v1.aulaholistica.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}


server {
    if ($host = v1.aulaholistica.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	listen 80;
	listen [::]:80;

	server_name v1.aulaholistica.com;
    return 404; # managed by Certbot


}`

Obviously I miss something

Thank you for your help

**Comment by MauricioOnetto** [comment]
I found it
I forgot replace vdo.ninja with my domain on the nginx conf
Now everything works perfect
Thank you!!!
