### ISSUE TITLE
FEATURE REQUEST: docker-compose support

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [steveseguin/obsninja#995]
Hi, it would be nice and simpler if I can self-host vdo.ninja using docker-compose

**Comment by steveseguin** [comment]
There's been a few users in the community who have created dockers for vdo.ninja; I think for example, https://github.com/Umlatt/vdo.ninja

I don't personally use docker, but if there's a growing need for one, I look to find time to create an official one .

Thank you for the request

**Comment by EsmailELBoBDev2** [comment]
Thank you. 
And if you are going to make a docker version, I hope it will be docker-compose because it's easier for me to manage it :joy:

**Comment by algorni** [comment]
+1 on having an officially supported fully offline docker composer version

**Comment by algorni** [comment]
@steveseguin  the Umlatt docker doesn't work.

**Comment by steveseguin** [comment]
Thank you for the request. I'm struggling to keep up with everything I'm already supporting, but I've added this to my list of things to do. 

I know this isn't a docker, but it's what I have at the moment for quick offline deployment support: https://github.com/steveseguin/offline_deployment

I rarely ever use docker, so it would take me some extra time to ramp up and figure out how to configure it all again.  

When doing offline deployments, you need to consider the need for self-signed certificates, etc, so the docker that is linked above probably won't work offline without modification.

**Comment by algorni** [comment]
OK @steveseguin  let me try to work on the offline deployment guide and put in place a docker compose for that, ok?

**Comment by steveseguin** [comment]
If you'd be able to improve the guide and/or add a docker compose option to the offline repo, that would be welcomed.

**Comment by algorni** [comment]
Using that as TURN Server:

```
docker run -d -p 3478:3478 -p 3478:3478/udp -p 5349:5349 -p 5349:5349/udp -p 49160-49200:49160-49200/udp \
    --name coturn  coturn/coturn --min-port=49160 --max-port=49200 --no-tls --no-auth 
```

**Comment by algorni** [comment]
https://github.com/algorni/vdo.ninja.local
